import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

import 'example_icons.dart';

List<IconData> randomIcons = [
  Icons.g_translate,
  Icons.backspace,
  Icons.backup,
  Icons.battery_alert,
  Icons.cached,
  Icons.cake,
  Icons.calendar_today,
  Icons.camera_enhance,
  Icons.camera_front,
  Icons.camera_rear,
  Icons.camera_roll,
  Icons.camera,
  Icons.cancel,
  Icons.card_giftcard,
  Icons.card_membership,
  Icons.card_travel,
  Icons.casino,
  Icons.cast_connected,
  Icons.calendar_view_day,
  Icons.call_end,
  Icons.call_made,
  Icons.call_merge,
  Icons.call_missed_outgoing,
  Icons.call_missed,
  Icons.call_received,
  Icons.call_split,
  Icons.call_to_action,
  Icons.call,
  Icons.camera_alt,
  Icons.laptop,
  Icons.last_page,
  Icons.launch,
  Icons.layers_clear,
  Icons.layers,
  Icons.mail_outline,
  Icons.mail,
  Icons.map,
  Icons.markunread_mailbox,
  Icons.markunread,
  Icons.maximize,
  Icons.cast,
  Icons.category,
  Icons.dashboard,
  Icons.data_usage,
  Icons.date_range,
  Icons.face,
  Icons.fast_forward,
  Icons.fast_rewind,
  Icons.fastfood,
  Icons.favorite_border,
  Icons.favorite,
  Icons.gamepad,
  Icons.games,
  Icons.gavel,
  Icons.label_important,
  Icons.label_outline,
  Icons.label,
  Icons.landscape,
  Icons.language,
  Icons.laptop_chromebook,
  Icons.laptop_mac,
  Icons.laptop_windows,
  Icons.wc,
  Icons.adb,
  Icons.add_a_photo,
  Icons.add_alarm,
  Icons.add_alert,
  Icons.add_box,
  Icons.add_call,
  Icons.add_circle_outline,
  Icons.add_circle,
  Icons.add_comment,
  Icons.add_location,
  Icons.panorama_vertical,
  Icons.panorama_wide_angle,
  Icons.panorama,
  Icons.party_mode,
  Icons.pause_circle_filled,
  Icons.pause_circle_outline,
  Icons.pause,
  Icons.payment,
  Icons.radio_button_checked,
  Icons.radio_button_unchecked,
  Icons.radio,
  Icons.nature_people,
  Icons.nature,
  Icons.navigate_before,
  Icons.navigate_next,
  Icons.navigation,
  Icons.pages,
  Icons.pageview,
  Icons.palette,
  Icons.pan_tool,
  Icons.panorama_fish_eye,
  Icons.panorama_horizontal,
  Icons.ac_unit,
  Icons.access_alarm,
  Icons.access_alarms,
  Icons.access_time,
  Icons.accessibility_new,
  Icons.accessibility,
  Icons.accessible_forward,
  Icons.accessible,
  Icons.account_balance_wallet,
  Icons.account_balance,
  Icons.account_box,
  Icons.delete_forever,
  Icons.delete_outline,
  Icons.delete_sweep,
  Icons.delete,
  Icons.departure_board,
  Icons.description,
  Icons.desktop_mac,
  Icons.desktop_windows,
  Icons.details,
  Icons.developer_board,
  Icons.developer_mode,
  Icons.rate_review,
  Icons.satellite,
  Icons.save_alt,
  Icons.save,
  Icons.tab_unselected,
  Icons.tab,
  Icons.table_chart,
  Icons.tablet_android,
  Icons.tablet_mac,
  Icons.tablet,
  Icons.tag_faces,
  Icons.tap_and_play,
  Icons.wallpaper,
  Icons.warning,
  Icons.watch_later,
  Icons.watch,
  Icons.wb_auto,
  Icons.wb_cloudy,
  Icons.wb_incandescent,
  Icons.wb_iridescent,
  Icons.wb_sunny,
  Icons.account_circle,
  Icons.scanner,
  Icons.scatter_plot,
  Icons.schedule,
  Icons.school,
  Icons.score,
  Icons.screen_lock_landscape,
  Icons.screen_lock_portrait,
  Icons.screen_lock_rotation,
  Icons.screen_rotation,
  Icons.screen_share,
  Icons.add_photo_alternate,
  Icons.add_shopping_cart,
  Icons.add_to_home_screen,
  Icons.add_to_photos,
  Icons.add_to_queue,
  Icons.add,
  Icons.adjust,
  Icons.edit_attributes,
  Icons.edit_location,
  Icons.edit,
  Icons.hd,
  Icons.hdr_off,
  Icons.hdr_on,
  Icons.hdr_strong,
  Icons.hdr_weak,
  Icons.sd_card,
  Icons.sd_storage,
  Icons.beach_access,
  Icons.beenhere,
  Icons.center_focus_strong,
  Icons.center_focus_weak,
  Icons.dehaze,
  Icons.device_hub,
  Icons.device_unknown,
  Icons.devices_other,
  Icons.devices,
  Icons.featured_play_list,
  Icons.featured_video,
  Icons.feedback,
  Icons.gesture,
  Icons.get_app,
  Icons.headset_mic,
  Icons.headset_off,
  Icons.headset,
  Icons.healing,
  Icons.hearing,
  Icons.help_outline,
  Icons.help,
  Icons.keyboard_arrow_down,
  Icons.keyboard_arrow_left,
  Icons.keyboard_arrow_right,
  Icons.keyboard_arrow_up,
  Icons.keyboard_backspace,
  Icons.keyboard_capslock,
  Icons.keyboard_hide,
  Icons.keyboard_return,
  Icons.keyboard_tab,
  Icons.keyboard_voice,
  Icons.keyboard,
  Icons.leak_add,
  Icons.leak_remove,
  Icons.lens,
  Icons.memory,
  Icons.menu,
  Icons.merge_type,
  Icons.message,
  Icons.near_me,
  Icons.network_cell,
  Icons.network_check,
  Icons.network_locked,
  Icons.network_wifi,
  Icons.new_releases,
  Icons.next_week,
  Icons.people_outline,
  Icons.people,
  Icons.perm_camera_mic,
  Icons.perm_contact_calendar,
  Icons.perm_data_setting,
  Icons.perm_device_information,
  Icons.perm_identity,
  Icons.perm_media,
  Icons.perm_phone_msg,
  Icons.perm_scan_wifi,
  Icons.person_add,
  Icons.person_outline,
  Icons.person_pin_circle,
  Icons.person_pin,
  Icons.person,
  Icons.personal_video,
  Icons.pets,
  Icons.receipt,
  Icons.recent_actors,
  Icons.record_voice_over,
  Icons.redeem,
  Icons.redo,
  Icons.refresh,
  Icons.remove_circle_outline,
  Icons.remove_circle,
  Icons.remove_from_queue,
  Icons.remove_red_eye,
  Icons.remove_shopping_cart,
  Icons.remove,
  Icons.reorder,
  Icons.repeat_one,
  Icons.repeat,
  Icons.replay_10,
  Icons.replay_30,
  Icons.replay_5,
  Icons.replay,
  Icons.reply_all,
  Icons.reply,
  Icons.report_off,
  Icons.report_problem,
  Icons.report,
  Icons.restaurant_menu,
  Icons.restaurant,
  Icons.restore_from_trash,
  Icons.restore_page,
  Icons.restore,
  Icons.search,
  Icons.security,
  Icons.select_all,
  Icons.send,
  Icons.sentiment_dissatisfied,
  Icons.sentiment_neutral,
  Icons.sentiment_satisfied,
  Icons.sentiment_very_dissatisfied,
  Icons.sentiment_very_satisfied,
  Icons.settings_applications,
  Icons.settings_backup_restore,
  Icons.settings_bluetooth,
  Icons.settings_brightness,
  Icons.settings_cell,
  Icons.settings_ethernet,
  Icons.settings_input_antenna,
  Icons.settings_input_component,
  Icons.settings_input_composite,
  Icons.settings_input_hdmi,
  Icons.settings_input_svideo,
  Icons.settings_overscan,
  Icons.settings_phone,
  Icons.settings_power,
  Icons.settings_remote,
  Icons.settings_system_daydream,
  Icons.settings_voice,
  Icons.settings,
  Icons.terrain,
  Icons.text_fields,
  Icons.text_format,
  Icons.text_rotate_up,
  Icons.text_rotate_vertical,
  Icons.text_rotation_angledown,
  Icons.text_rotation_angleup,
  Icons.battery_charging_full,
  Icons.text_rotation_down,
  Icons.text_rotation_none,
  Icons.textsms,
  Icons.texture,
  Icons.verified_user,
  Icons.vertical_align_bottom,
  Icons.vertical_align_center,
  Icons.vertical_align_top,
  Icons.web_asset,
  Icons.web,
  Icons.weekend,
  Icons.nfc,
  Icons.offline_bolt,
  Icons.offline_pin,
  Icons.change_history,
  Icons.chat_bubble_outline,
  Icons.chat_bubble,
  Icons.chat,
  Icons.check_box_outline_blank,
  Icons.check_box,
  Icons.check_circle_outline,
  Icons.check_circle,
];

final icons = <FAIcons>[
  FAIcons(FontAwesomeIcons.fiveHundredPx, 'fiveHundredPx'),
  FAIcons(FontAwesomeIcons.accessibleIcon, 'accessibleIcon'),
  FAIcons(FontAwesomeIcons.accusoft, 'accusoft'),
  FAIcons(
      FontAwesomeIcons.acquisitionsIncorporated, 'acquisitionsIncorporated'),
  FAIcons(FontAwesomeIcons.ad, 'ad'),
  FAIcons(FontAwesomeIcons.addressBook, 'addressBook'),
  FAIcons(FontAwesomeIcons.solidAddressBook, 'solidAddressBook'),
  FAIcons(FontAwesomeIcons.addressCard, 'addressCard'),
  FAIcons(FontAwesomeIcons.solidAddressCard, 'solidAddressCard'),
  FAIcons(FontAwesomeIcons.adjust, 'adjust'),
  FAIcons(FontAwesomeIcons.adn, 'adn'),
  FAIcons(FontAwesomeIcons.adobe, 'adobe'),
  FAIcons(FontAwesomeIcons.adversal, 'adversal'),
  FAIcons(FontAwesomeIcons.affiliatetheme, 'affiliatetheme'),
  FAIcons(FontAwesomeIcons.airFreshener, 'airFreshener'),
  FAIcons(FontAwesomeIcons.algolia, 'algolia'),
  FAIcons(FontAwesomeIcons.alignCenter, 'alignCenter'),
  FAIcons(FontAwesomeIcons.alignJustify, 'alignJustify'),
  FAIcons(FontAwesomeIcons.alignLeft, 'alignLeft'),
  FAIcons(FontAwesomeIcons.alignRight, 'alignRight'),
  FAIcons(FontAwesomeIcons.alipay, 'alipay'),
  FAIcons(FontAwesomeIcons.allergies, 'allergies'),
  FAIcons(FontAwesomeIcons.amazon, 'amazon'),
  FAIcons(FontAwesomeIcons.amazonPay, 'amazonPay'),
  FAIcons(FontAwesomeIcons.ambulance, 'ambulance'),
  FAIcons(FontAwesomeIcons.americanSignLanguageInterpreting,
      'americanSignLanguageInterpreting'),
  FAIcons(FontAwesomeIcons.amilia, 'amilia'),
  FAIcons(FontAwesomeIcons.anchor, 'anchor'),
  FAIcons(FontAwesomeIcons.android, 'android'),
  FAIcons(FontAwesomeIcons.angellist, 'angellist'),
  FAIcons(FontAwesomeIcons.angleDoubleDown, 'angleDoubleDown'),
  FAIcons(FontAwesomeIcons.angleDoubleLeft, 'angleDoubleLeft'),
  FAIcons(FontAwesomeIcons.angleDoubleRight, 'angleDoubleRight'),
  FAIcons(FontAwesomeIcons.angleDoubleUp, 'angleDoubleUp'),
  FAIcons(FontAwesomeIcons.angleDown, 'angleDown'),
  FAIcons(FontAwesomeIcons.angleLeft, 'angleLeft'),
  FAIcons(FontAwesomeIcons.angleRight, 'angleRight'),
  FAIcons(FontAwesomeIcons.angleUp, 'angleUp'),
  FAIcons(FontAwesomeIcons.angry, 'angry'),
  FAIcons(FontAwesomeIcons.solidAngry, 'solidAngry'),
  FAIcons(FontAwesomeIcons.angrycreative, 'angrycreative'),
  FAIcons(FontAwesomeIcons.angular, 'angular'),
  FAIcons(FontAwesomeIcons.ankh, 'ankh'),
  FAIcons(FontAwesomeIcons.appStore, 'appStore'),
  FAIcons(FontAwesomeIcons.appStoreIos, 'appStoreIos'),
  FAIcons(FontAwesomeIcons.apper, 'apper'),
  FAIcons(FontAwesomeIcons.apple, 'apple'),
  FAIcons(FontAwesomeIcons.appleAlt, 'appleAlt'),
  FAIcons(FontAwesomeIcons.applePay, 'applePay'),
  FAIcons(FontAwesomeIcons.archive, 'archive'),
  FAIcons(FontAwesomeIcons.archway, 'archway'),
  FAIcons(FontAwesomeIcons.arrowAltCircleDown, 'arrowAltCircleDown'),
  FAIcons(FontAwesomeIcons.solidArrowAltCircleDown, 'solidArrowAltCircleDown'),
  FAIcons(FontAwesomeIcons.arrowAltCircleLeft, 'arrowAltCircleLeft'),
  FAIcons(FontAwesomeIcons.solidArrowAltCircleLeft, 'solidArrowAltCircleLeft'),
  FAIcons(FontAwesomeIcons.arrowAltCircleRight, 'arrowAltCircleRight'),
  FAIcons(
      FontAwesomeIcons.solidArrowAltCircleRight, 'solidArrowAltCircleRight'),
  FAIcons(FontAwesomeIcons.arrowAltCircleUp, 'arrowAltCircleUp'),
  FAIcons(FontAwesomeIcons.solidArrowAltCircleUp, 'solidArrowAltCircleUp'),
  FAIcons(FontAwesomeIcons.arrowCircleDown, 'arrowCircleDown'),
  FAIcons(FontAwesomeIcons.arrowCircleLeft, 'arrowCircleLeft'),
  FAIcons(FontAwesomeIcons.arrowCircleRight, 'arrowCircleRight'),
  FAIcons(FontAwesomeIcons.arrowCircleUp, 'arrowCircleUp'),
  FAIcons(FontAwesomeIcons.arrowDown, 'arrowDown'),
  FAIcons(FontAwesomeIcons.arrowLeft, 'arrowLeft'),
  FAIcons(FontAwesomeIcons.arrowRight, 'arrowRight'),
  FAIcons(FontAwesomeIcons.arrowUp, 'arrowUp'),
  FAIcons(FontAwesomeIcons.arrowsAlt, 'arrowsAlt'),
  FAIcons(FontAwesomeIcons.arrowsAltH, 'arrowsAltH'),
  FAIcons(FontAwesomeIcons.arrowsAltV, 'arrowsAltV'),
  FAIcons(FontAwesomeIcons.artstation, 'artstation'),
  FAIcons(
      FontAwesomeIcons.assistiveListeningSystems, 'assistiveListeningSystems'),
  FAIcons(FontAwesomeIcons.asterisk, 'asterisk'),
  FAIcons(FontAwesomeIcons.asymmetrik, 'asymmetrik'),
  FAIcons(FontAwesomeIcons.at, 'at'),
  FAIcons(FontAwesomeIcons.atlas, 'atlas'),
  FAIcons(FontAwesomeIcons.atlassian, 'atlassian'),
  FAIcons(FontAwesomeIcons.atom, 'atom'),
  FAIcons(FontAwesomeIcons.audible, 'audible'),
  FAIcons(FontAwesomeIcons.audioDescription, 'audioDescription'),
  FAIcons(FontAwesomeIcons.autoprefixer, 'autoprefixer'),
  FAIcons(FontAwesomeIcons.avianex, 'avianex'),
  FAIcons(FontAwesomeIcons.aviato, 'aviato'),
  FAIcons(FontAwesomeIcons.award, 'award'),
  FAIcons(FontAwesomeIcons.aws, 'aws'),
  FAIcons(FontAwesomeIcons.baby, 'baby'),
  FAIcons(FontAwesomeIcons.babyCarriage, 'babyCarriage'),
  FAIcons(FontAwesomeIcons.backspace, 'backspace'),
  FAIcons(FontAwesomeIcons.backward, 'backward'),
  FAIcons(FontAwesomeIcons.bacon, 'bacon'),
  FAIcons(FontAwesomeIcons.balanceScale, 'balanceScale'),
  FAIcons(FontAwesomeIcons.ban, 'ban'),
  FAIcons(FontAwesomeIcons.bandAid, 'bandAid'),
  FAIcons(FontAwesomeIcons.bandcamp, 'bandcamp'),
  FAIcons(FontAwesomeIcons.barcode, 'barcode'),
  FAIcons(FontAwesomeIcons.bars, 'bars'),
  FAIcons(FontAwesomeIcons.baseballBall, 'baseballBall'),
  FAIcons(FontAwesomeIcons.basketballBall, 'basketballBall'),
  FAIcons(FontAwesomeIcons.bath, 'bath'),
  FAIcons(FontAwesomeIcons.batteryEmpty, 'batteryEmpty'),
  FAIcons(FontAwesomeIcons.batteryFull, 'batteryFull'),
  FAIcons(FontAwesomeIcons.batteryHalf, 'batteryHalf'),
  FAIcons(FontAwesomeIcons.batteryQuarter, 'batteryQuarter'),
  FAIcons(FontAwesomeIcons.batteryThreeQuarters, 'batteryThreeQuarters'),
  FAIcons(FontAwesomeIcons.bed, 'bed'),
  FAIcons(FontAwesomeIcons.beer, 'beer'),
  FAIcons(FontAwesomeIcons.behance, 'behance'),
  FAIcons(FontAwesomeIcons.behanceSquare, 'behanceSquare'),
  FAIcons(FontAwesomeIcons.bell, 'bell'),
  FAIcons(FontAwesomeIcons.solidBell, 'solidBell'),
  FAIcons(FontAwesomeIcons.bellSlash, 'bellSlash'),
  FAIcons(FontAwesomeIcons.solidBellSlash, 'solidBellSlash'),
  FAIcons(FontAwesomeIcons.bezierCurve, 'bezierCurve'),
  FAIcons(FontAwesomeIcons.bible, 'bible'),
  FAIcons(FontAwesomeIcons.bicycle, 'bicycle'),
  FAIcons(FontAwesomeIcons.bimobject, 'bimobject'),
  FAIcons(FontAwesomeIcons.binoculars, 'binoculars'),
  FAIcons(FontAwesomeIcons.biohazard, 'biohazard'),
  FAIcons(FontAwesomeIcons.birthdayCake, 'birthdayCake'),
  FAIcons(FontAwesomeIcons.bitbucket, 'bitbucket'),
  FAIcons(FontAwesomeIcons.bitcoin, 'bitcoin'),
  FAIcons(FontAwesomeIcons.bity, 'bity'),
  FAIcons(FontAwesomeIcons.blackTie, 'blackTie'),
  FAIcons(FontAwesomeIcons.blackberry, 'blackberry'),
  FAIcons(FontAwesomeIcons.blender, 'blender'),
  FAIcons(FontAwesomeIcons.blenderPhone, 'blenderPhone'),
  FAIcons(FontAwesomeIcons.blind, 'blind'),
  FAIcons(FontAwesomeIcons.blog, 'blog'),
  FAIcons(FontAwesomeIcons.blogger, 'blogger'),
  FAIcons(FontAwesomeIcons.bloggerB, 'bloggerB'),
  FAIcons(FontAwesomeIcons.bluetooth, 'bluetooth'),
  FAIcons(FontAwesomeIcons.bluetoothB, 'bluetoothB'),
  FAIcons(FontAwesomeIcons.bold, 'bold'),
  FAIcons(FontAwesomeIcons.bolt, 'bolt'),
  FAIcons(FontAwesomeIcons.bomb, 'bomb'),
  FAIcons(FontAwesomeIcons.bone, 'bone'),
  FAIcons(FontAwesomeIcons.bong, 'bong'),
  FAIcons(FontAwesomeIcons.book, 'book'),
  FAIcons(FontAwesomeIcons.bookDead, 'bookDead'),
  FAIcons(FontAwesomeIcons.bookMedical, 'bookMedical'),
  FAIcons(FontAwesomeIcons.bookOpen, 'bookOpen'),
  FAIcons(FontAwesomeIcons.bookReader, 'bookReader'),
  FAIcons(FontAwesomeIcons.bookmark, 'bookmark'),
  FAIcons(FontAwesomeIcons.solidBookmark, 'solidBookmark'),
  FAIcons(FontAwesomeIcons.bowlingBall, 'bowlingBall'),
  FAIcons(FontAwesomeIcons.box, 'box'),
  FAIcons(FontAwesomeIcons.boxOpen, 'boxOpen'),
  FAIcons(FontAwesomeIcons.boxes, 'boxes'),
  FAIcons(FontAwesomeIcons.braille, 'braille'),
  FAIcons(FontAwesomeIcons.brain, 'brain'),
  FAIcons(FontAwesomeIcons.breadSlice, 'breadSlice'),
  FAIcons(FontAwesomeIcons.briefcase, 'briefcase'),
  FAIcons(FontAwesomeIcons.briefcaseMedical, 'briefcaseMedical'),
  FAIcons(FontAwesomeIcons.broadcastTower, 'broadcastTower'),
  FAIcons(FontAwesomeIcons.broom, 'broom'),
  FAIcons(FontAwesomeIcons.brush, 'brush'),
  FAIcons(FontAwesomeIcons.btc, 'btc'),
  FAIcons(FontAwesomeIcons.bug, 'bug'),
  FAIcons(FontAwesomeIcons.building, 'building'),
  FAIcons(FontAwesomeIcons.solidBuilding, 'solidBuilding'),
  FAIcons(FontAwesomeIcons.bullhorn, 'bullhorn'),
  FAIcons(FontAwesomeIcons.bullseye, 'bullseye'),
  FAIcons(FontAwesomeIcons.burn, 'burn'),
  FAIcons(FontAwesomeIcons.buromobelexperte, 'buromobelexperte'),
  FAIcons(FontAwesomeIcons.bus, 'bus'),
  FAIcons(FontAwesomeIcons.busAlt, 'busAlt'),
  FAIcons(FontAwesomeIcons.businessTime, 'businessTime'),
  FAIcons(FontAwesomeIcons.buysellads, 'buysellads'),
  FAIcons(FontAwesomeIcons.calculator, 'calculator'),
  FAIcons(FontAwesomeIcons.calendar, 'calendar'),
  FAIcons(FontAwesomeIcons.solidCalendar, 'solidCalendar'),
  FAIcons(FontAwesomeIcons.calendarAlt, 'calendarAlt'),
  FAIcons(FontAwesomeIcons.solidCalendarAlt, 'solidCalendarAlt'),
  FAIcons(FontAwesomeIcons.calendarCheck, 'calendarCheck'),
  FAIcons(FontAwesomeIcons.solidCalendarCheck, 'solidCalendarCheck'),
  FAIcons(FontAwesomeIcons.calendarDay, 'calendarDay'),
  FAIcons(FontAwesomeIcons.calendarMinus, 'calendarMinus'),
  FAIcons(FontAwesomeIcons.solidCalendarMinus, 'solidCalendarMinus'),
  FAIcons(FontAwesomeIcons.calendarPlus, 'calendarPlus'),
  FAIcons(FontAwesomeIcons.solidCalendarPlus, 'solidCalendarPlus'),
  FAIcons(FontAwesomeIcons.calendarTimes, 'calendarTimes'),
  FAIcons(FontAwesomeIcons.solidCalendarTimes, 'solidCalendarTimes'),
  FAIcons(FontAwesomeIcons.calendarWeek, 'calendarWeek'),
  FAIcons(FontAwesomeIcons.camera, 'camera'),
  FAIcons(FontAwesomeIcons.cameraRetro, 'cameraRetro'),
  FAIcons(FontAwesomeIcons.campground, 'campground'),
  FAIcons(FontAwesomeIcons.canadianMapleLeaf, 'canadianMapleLeaf'),
  FAIcons(FontAwesomeIcons.candyCane, 'candyCane'),
  FAIcons(FontAwesomeIcons.cannabis, 'cannabis'),
  FAIcons(FontAwesomeIcons.capsules, 'capsules'),
  FAIcons(FontAwesomeIcons.car, 'car'),
  FAIcons(FontAwesomeIcons.carAlt, 'carAlt'),
  FAIcons(FontAwesomeIcons.carBattery, 'carBattery'),
  FAIcons(FontAwesomeIcons.carCrash, 'carCrash'),
  FAIcons(FontAwesomeIcons.carSide, 'carSide'),
  FAIcons(FontAwesomeIcons.caretDown, 'caretDown'),
  FAIcons(FontAwesomeIcons.caretLeft, 'caretLeft'),
  FAIcons(FontAwesomeIcons.caretRight, 'caretRight'),
  FAIcons(FontAwesomeIcons.caretSquareDown, 'caretSquareDown'),
  FAIcons(FontAwesomeIcons.solidCaretSquareDown, 'solidCaretSquareDown'),
  FAIcons(FontAwesomeIcons.caretSquareLeft, 'caretSquareLeft'),
  FAIcons(FontAwesomeIcons.solidCaretSquareLeft, 'solidCaretSquareLeft'),
  FAIcons(FontAwesomeIcons.caretSquareRight, 'caretSquareRight'),
  FAIcons(FontAwesomeIcons.solidCaretSquareRight, 'solidCaretSquareRight'),
  FAIcons(FontAwesomeIcons.caretSquareUp, 'caretSquareUp'),
  FAIcons(FontAwesomeIcons.solidCaretSquareUp, 'solidCaretSquareUp'),
  FAIcons(FontAwesomeIcons.caretUp, 'caretUp'),
  FAIcons(FontAwesomeIcons.carrot, 'carrot'),
  FAIcons(FontAwesomeIcons.cartArrowDown, 'cartArrowDown'),
  FAIcons(FontAwesomeIcons.cartPlus, 'cartPlus'),
  FAIcons(FontAwesomeIcons.cashRegister, 'cashRegister'),
  FAIcons(FontAwesomeIcons.cat, 'cat'),
  FAIcons(FontAwesomeIcons.ccAmazonPay, 'ccAmazonPay'),
  FAIcons(FontAwesomeIcons.ccAmex, 'ccAmex'),
  FAIcons(FontAwesomeIcons.ccApplePay, 'ccApplePay'),
  FAIcons(FontAwesomeIcons.ccDinersClub, 'ccDinersClub'),
  FAIcons(FontAwesomeIcons.ccDiscover, 'ccDiscover'),
  FAIcons(FontAwesomeIcons.ccJcb, 'ccJcb'),
  FAIcons(FontAwesomeIcons.ccMastercard, 'ccMastercard'),
  FAIcons(FontAwesomeIcons.ccPaypal, 'ccPaypal'),
  FAIcons(FontAwesomeIcons.ccStripe, 'ccStripe'),
  FAIcons(FontAwesomeIcons.ccVisa, 'ccVisa'),
  FAIcons(FontAwesomeIcons.centercode, 'centercode'),
  FAIcons(FontAwesomeIcons.centos, 'centos'),
  FAIcons(FontAwesomeIcons.certificate, 'certificate'),
  FAIcons(FontAwesomeIcons.chair, 'chair'),
  FAIcons(FontAwesomeIcons.chalkboard, 'chalkboard'),
  FAIcons(FontAwesomeIcons.chalkboardTeacher, 'chalkboardTeacher'),
  FAIcons(FontAwesomeIcons.chargingStation, 'chargingStation'),
  FAIcons(FontAwesomeIcons.chartArea, 'chartArea'),
  FAIcons(FontAwesomeIcons.chartBar, 'chartBar'),
  FAIcons(FontAwesomeIcons.solidChartBar, 'solidChartBar'),
  FAIcons(FontAwesomeIcons.chartLine, 'chartLine'),
  FAIcons(FontAwesomeIcons.chartPie, 'chartPie'),
  FAIcons(FontAwesomeIcons.check, 'check'),
  FAIcons(FontAwesomeIcons.checkCircle, 'checkCircle'),
  FAIcons(FontAwesomeIcons.solidCheckCircle, 'solidCheckCircle'),
  FAIcons(FontAwesomeIcons.checkDouble, 'checkDouble'),
  FAIcons(FontAwesomeIcons.checkSquare, 'checkSquare'),
  FAIcons(FontAwesomeIcons.solidCheckSquare, 'solidCheckSquare'),
  FAIcons(FontAwesomeIcons.cheese, 'cheese'),
  FAIcons(FontAwesomeIcons.chess, 'chess'),
  FAIcons(FontAwesomeIcons.chessBishop, 'chessBishop'),
  FAIcons(FontAwesomeIcons.chessBoard, 'chessBoard'),
  FAIcons(FontAwesomeIcons.chessKing, 'chessKing'),
  FAIcons(FontAwesomeIcons.chessKnight, 'chessKnight'),
  FAIcons(FontAwesomeIcons.chessPawn, 'chessPawn'),
  FAIcons(FontAwesomeIcons.chessQueen, 'chessQueen'),
  FAIcons(FontAwesomeIcons.chessRook, 'chessRook'),
  FAIcons(FontAwesomeIcons.chevronCircleDown, 'chevronCircleDown'),
  FAIcons(FontAwesomeIcons.chevronCircleLeft, 'chevronCircleLeft'),
  FAIcons(FontAwesomeIcons.chevronCircleRight, 'chevronCircleRight'),
  FAIcons(FontAwesomeIcons.chevronCircleUp, 'chevronCircleUp'),
  FAIcons(FontAwesomeIcons.chevronDown, 'chevronDown'),
  FAIcons(FontAwesomeIcons.chevronLeft, 'chevronLeft'),
  FAIcons(FontAwesomeIcons.chevronRight, 'chevronRight'),
  FAIcons(FontAwesomeIcons.chevronUp, 'chevronUp'),
  FAIcons(FontAwesomeIcons.child, 'child'),
  FAIcons(FontAwesomeIcons.chrome, 'chrome'),
  FAIcons(FontAwesomeIcons.church, 'church'),
  FAIcons(FontAwesomeIcons.circle, 'circle'),
  FAIcons(FontAwesomeIcons.solidCircle, 'solidCircle'),
  FAIcons(FontAwesomeIcons.circleNotch, 'circleNotch'),
  FAIcons(FontAwesomeIcons.city, 'city'),
  FAIcons(FontAwesomeIcons.clinicMedical, 'clinicMedical'),
  FAIcons(FontAwesomeIcons.clipboard, 'clipboard'),
  FAIcons(FontAwesomeIcons.solidClipboard, 'solidClipboard'),
  FAIcons(FontAwesomeIcons.clipboardCheck, 'clipboardCheck'),
  FAIcons(FontAwesomeIcons.clipboardList, 'clipboardList'),
  FAIcons(FontAwesomeIcons.clock, 'clock'),
  FAIcons(FontAwesomeIcons.solidClock, 'solidClock'),
  FAIcons(FontAwesomeIcons.clone, 'clone'),
  FAIcons(FontAwesomeIcons.solidClone, 'solidClone'),
  FAIcons(FontAwesomeIcons.closedCaptioning, 'closedCaptioning'),
  FAIcons(FontAwesomeIcons.solidClosedCaptioning, 'solidClosedCaptioning'),
  FAIcons(FontAwesomeIcons.cloud, 'cloud'),
  FAIcons(FontAwesomeIcons.cloudDownloadAlt, 'cloudDownloadAlt'),
  FAIcons(FontAwesomeIcons.cloudMeatball, 'cloudMeatball'),
  FAIcons(FontAwesomeIcons.cloudMoon, 'cloudMoon'),
  FAIcons(FontAwesomeIcons.cloudMoonRain, 'cloudMoonRain'),
  FAIcons(FontAwesomeIcons.cloudRain, 'cloudRain'),
  FAIcons(FontAwesomeIcons.cloudShowersHeavy, 'cloudShowersHeavy'),
  FAIcons(FontAwesomeIcons.cloudSun, 'cloudSun'),
  FAIcons(FontAwesomeIcons.cloudSunRain, 'cloudSunRain'),
  FAIcons(FontAwesomeIcons.cloudUploadAlt, 'cloudUploadAlt'),
  FAIcons(FontAwesomeIcons.cloudscale, 'cloudscale'),
  FAIcons(FontAwesomeIcons.cloudsmith, 'cloudsmith'),
  FAIcons(FontAwesomeIcons.cloudversify, 'cloudversify'),
  FAIcons(FontAwesomeIcons.cocktail, 'cocktail'),
  FAIcons(FontAwesomeIcons.code, 'code'),
  FAIcons(FontAwesomeIcons.codeBranch, 'codeBranch'),
  FAIcons(FontAwesomeIcons.codepen, 'codepen'),
  FAIcons(FontAwesomeIcons.codiepie, 'codiepie'),
  FAIcons(FontAwesomeIcons.coffee, 'coffee'),
  FAIcons(FontAwesomeIcons.cog, 'cog'),
  FAIcons(FontAwesomeIcons.cogs, 'cogs'),
  FAIcons(FontAwesomeIcons.coins, 'coins'),
  FAIcons(FontAwesomeIcons.columns, 'columns'),
  FAIcons(FontAwesomeIcons.comment, 'comment'),
  FAIcons(FontAwesomeIcons.solidComment, 'solidComment'),
  FAIcons(FontAwesomeIcons.commentAlt, 'commentAlt'),
  FAIcons(FontAwesomeIcons.solidCommentAlt, 'solidCommentAlt'),
  FAIcons(FontAwesomeIcons.commentDollar, 'commentDollar'),
  FAIcons(FontAwesomeIcons.commentDots, 'commentDots'),
  FAIcons(FontAwesomeIcons.solidCommentDots, 'solidCommentDots'),
  FAIcons(FontAwesomeIcons.commentMedical, 'commentMedical'),
  FAIcons(FontAwesomeIcons.commentSlash, 'commentSlash'),
  FAIcons(FontAwesomeIcons.comments, 'comments'),
  FAIcons(FontAwesomeIcons.solidComments, 'solidComments'),
  FAIcons(FontAwesomeIcons.commentsDollar, 'commentsDollar'),
  FAIcons(FontAwesomeIcons.compactDisc, 'compactDisc'),
  FAIcons(FontAwesomeIcons.compass, 'compass'),
  FAIcons(FontAwesomeIcons.solidCompass, 'solidCompass'),
  FAIcons(FontAwesomeIcons.compress, 'compress'),
  FAIcons(FontAwesomeIcons.compressArrowsAlt, 'compressArrowsAlt'),
  FAIcons(FontAwesomeIcons.conciergeBell, 'conciergeBell'),
  FAIcons(FontAwesomeIcons.confluence, 'confluence'),
  FAIcons(FontAwesomeIcons.connectdevelop, 'connectdevelop'),
  FAIcons(FontAwesomeIcons.contao, 'contao'),
  FAIcons(FontAwesomeIcons.cookie, 'cookie'),
  FAIcons(FontAwesomeIcons.cookieBite, 'cookieBite'),
  FAIcons(FontAwesomeIcons.copy, 'copy'),
  FAIcons(FontAwesomeIcons.solidCopy, 'solidCopy'),
  FAIcons(FontAwesomeIcons.copyright, 'copyright'),
  FAIcons(FontAwesomeIcons.solidCopyright, 'solidCopyright'),
  FAIcons(FontAwesomeIcons.couch, 'couch'),
  FAIcons(FontAwesomeIcons.cpanel, 'cpanel'),
  FAIcons(FontAwesomeIcons.creativeCommons, 'creativeCommons'),
  FAIcons(FontAwesomeIcons.creativeCommonsBy, 'creativeCommonsBy'),
  FAIcons(FontAwesomeIcons.creativeCommonsNc, 'creativeCommonsNc'),
  FAIcons(FontAwesomeIcons.creativeCommonsNcEu, 'creativeCommonsNcEu'),
  FAIcons(FontAwesomeIcons.creativeCommonsNcJp, 'creativeCommonsNcJp'),
  FAIcons(FontAwesomeIcons.creativeCommonsNd, 'creativeCommonsNd'),
  FAIcons(FontAwesomeIcons.creativeCommonsPd, 'creativeCommonsPd'),
  FAIcons(FontAwesomeIcons.creativeCommonsPdAlt, 'creativeCommonsPdAlt'),
  FAIcons(FontAwesomeIcons.creativeCommonsRemix, 'creativeCommonsRemix'),
  FAIcons(FontAwesomeIcons.creativeCommonsSa, 'creativeCommonsSa'),
  FAIcons(FontAwesomeIcons.creativeCommonsSampling, 'creativeCommonsSampling'),
  FAIcons(FontAwesomeIcons.creativeCommonsSamplingPlus,
      'creativeCommonsSamplingPlus'),
  FAIcons(FontAwesomeIcons.creativeCommonsShare, 'creativeCommonsShare'),
  FAIcons(FontAwesomeIcons.creativeCommonsZero, 'creativeCommonsZero'),
  FAIcons(FontAwesomeIcons.creditCard, 'creditCard'),
  FAIcons(FontAwesomeIcons.solidCreditCard, 'solidCreditCard'),
  FAIcons(FontAwesomeIcons.criticalRole, 'criticalRole'),
  FAIcons(FontAwesomeIcons.crop, 'crop'),
  FAIcons(FontAwesomeIcons.cropAlt, 'cropAlt'),
  FAIcons(FontAwesomeIcons.cross, 'cross'),
  FAIcons(FontAwesomeIcons.crosshairs, 'crosshairs'),
  FAIcons(FontAwesomeIcons.crow, 'crow'),
  FAIcons(FontAwesomeIcons.crown, 'crown'),
  FAIcons(FontAwesomeIcons.crutch, 'crutch'),
  FAIcons(FontAwesomeIcons.css3, 'css3'),
  FAIcons(FontAwesomeIcons.css3Alt, 'css3Alt'),
  FAIcons(FontAwesomeIcons.cube, 'cube'),
  FAIcons(FontAwesomeIcons.cubes, 'cubes'),
  FAIcons(FontAwesomeIcons.cut, 'cut'),
  FAIcons(FontAwesomeIcons.cuttlefish, 'cuttlefish'),
  FAIcons(FontAwesomeIcons.dAndD, 'dAndD'),
  FAIcons(FontAwesomeIcons.dAndDBeyond, 'dAndDBeyond'),
  FAIcons(FontAwesomeIcons.dashcube, 'dashcube'),
  FAIcons(FontAwesomeIcons.database, 'database'),
  FAIcons(FontAwesomeIcons.deaf, 'deaf'),
  FAIcons(FontAwesomeIcons.delicious, 'delicious'),
  FAIcons(FontAwesomeIcons.democrat, 'democrat'),
  FAIcons(FontAwesomeIcons.deploydog, 'deploydog'),
  FAIcons(FontAwesomeIcons.deskpro, 'deskpro'),
  FAIcons(FontAwesomeIcons.desktop, 'desktop'),
  FAIcons(FontAwesomeIcons.dev, 'dev'),
  FAIcons(FontAwesomeIcons.deviantart, 'deviantart'),
  FAIcons(FontAwesomeIcons.dharmachakra, 'dharmachakra'),
  FAIcons(FontAwesomeIcons.dhl, 'dhl'),
  FAIcons(FontAwesomeIcons.diagnoses, 'diagnoses'),
  FAIcons(FontAwesomeIcons.diaspora, 'diaspora'),
  FAIcons(FontAwesomeIcons.dice, 'dice'),
  FAIcons(FontAwesomeIcons.diceD20, 'diceD20'),
  FAIcons(FontAwesomeIcons.diceD6, 'diceD6'),
  FAIcons(FontAwesomeIcons.diceFive, 'diceFive'),
  FAIcons(FontAwesomeIcons.diceFour, 'diceFour'),
  FAIcons(FontAwesomeIcons.diceOne, 'diceOne'),
  FAIcons(FontAwesomeIcons.diceSix, 'diceSix'),
  FAIcons(FontAwesomeIcons.diceThree, 'diceThree'),
  FAIcons(FontAwesomeIcons.diceTwo, 'diceTwo'),
  FAIcons(FontAwesomeIcons.digg, 'digg'),
  FAIcons(FontAwesomeIcons.digitalOcean, 'digitalOcean'),
  FAIcons(FontAwesomeIcons.digitalTachograph, 'digitalTachograph'),
  FAIcons(FontAwesomeIcons.directions, 'directions'),
  FAIcons(FontAwesomeIcons.discord, 'discord'),
  FAIcons(FontAwesomeIcons.discourse, 'discourse'),
  FAIcons(FontAwesomeIcons.divide, 'divide'),
  FAIcons(FontAwesomeIcons.dizzy, 'dizzy'),
  FAIcons(FontAwesomeIcons.solidDizzy, 'solidDizzy'),
  FAIcons(FontAwesomeIcons.dna, 'dna'),
  FAIcons(FontAwesomeIcons.dochub, 'dochub'),
  FAIcons(FontAwesomeIcons.docker, 'docker'),
  FAIcons(FontAwesomeIcons.dog, 'dog'),
  FAIcons(FontAwesomeIcons.dollarSign, 'dollarSign'),
  FAIcons(FontAwesomeIcons.dolly, 'dolly'),
  FAIcons(FontAwesomeIcons.dollyFlatbed, 'dollyFlatbed'),
  FAIcons(FontAwesomeIcons.donate, 'donate'),
  FAIcons(FontAwesomeIcons.doorClosed, 'doorClosed'),
  FAIcons(FontAwesomeIcons.doorOpen, 'doorOpen'),
  FAIcons(FontAwesomeIcons.dotCircle, 'dotCircle'),
  FAIcons(FontAwesomeIcons.solidDotCircle, 'solidDotCircle'),
  FAIcons(FontAwesomeIcons.dove, 'dove'),
  FAIcons(FontAwesomeIcons.download, 'download'),
  FAIcons(FontAwesomeIcons.draft2digital, 'draft2digital'),
  FAIcons(FontAwesomeIcons.draftingCompass, 'draftingCompass'),
  FAIcons(FontAwesomeIcons.dragon, 'dragon'),
  FAIcons(FontAwesomeIcons.drawPolygon, 'drawPolygon'),
  FAIcons(FontAwesomeIcons.dribbble, 'dribbble'),
  FAIcons(FontAwesomeIcons.dribbbleSquare, 'dribbbleSquare'),
  FAIcons(FontAwesomeIcons.dropbox, 'dropbox'),
  FAIcons(FontAwesomeIcons.drum, 'drum'),
  FAIcons(FontAwesomeIcons.drumSteelpan, 'drumSteelpan'),
  FAIcons(FontAwesomeIcons.drumstickBite, 'drumstickBite'),
  FAIcons(FontAwesomeIcons.drupal, 'drupal'),
  FAIcons(FontAwesomeIcons.dumbbell, 'dumbbell'),
  FAIcons(FontAwesomeIcons.dumpster, 'dumpster'),
  FAIcons(FontAwesomeIcons.dumpsterFire, 'dumpsterFire'),
  FAIcons(FontAwesomeIcons.dungeon, 'dungeon'),
  FAIcons(FontAwesomeIcons.dyalog, 'dyalog'),
  FAIcons(FontAwesomeIcons.earlybirds, 'earlybirds'),
  FAIcons(FontAwesomeIcons.ebay, 'ebay'),
  FAIcons(FontAwesomeIcons.edge, 'edge'),
  FAIcons(FontAwesomeIcons.edit, 'edit'),
  FAIcons(FontAwesomeIcons.solidEdit, 'solidEdit'),
  FAIcons(FontAwesomeIcons.egg, 'egg'),
  FAIcons(FontAwesomeIcons.eject, 'eject'),
  FAIcons(FontAwesomeIcons.elementor, 'elementor'),
  FAIcons(FontAwesomeIcons.ellipsisH, 'ellipsisH'),
  FAIcons(FontAwesomeIcons.ellipsisV, 'ellipsisV'),
  FAIcons(FontAwesomeIcons.ello, 'ello'),
  FAIcons(FontAwesomeIcons.ember, 'ember'),
  FAIcons(FontAwesomeIcons.empire, 'empire'),
  FAIcons(FontAwesomeIcons.envelope, 'envelope'),
  FAIcons(FontAwesomeIcons.solidEnvelope, 'solidEnvelope'),
  FAIcons(FontAwesomeIcons.envelopeOpen, 'envelopeOpen'),
  FAIcons(FontAwesomeIcons.solidEnvelopeOpen, 'solidEnvelopeOpen'),
  FAIcons(FontAwesomeIcons.envelopeOpenText, 'envelopeOpenText'),
  FAIcons(FontAwesomeIcons.envelopeSquare, 'envelopeSquare'),
  FAIcons(FontAwesomeIcons.envira, 'envira'),
  FAIcons(FontAwesomeIcons.equals, 'equals'),
  FAIcons(FontAwesomeIcons.eraser, 'eraser'),
  FAIcons(FontAwesomeIcons.erlang, 'erlang'),
  FAIcons(FontAwesomeIcons.ethereum, 'ethereum'),
  FAIcons(FontAwesomeIcons.ethernet, 'ethernet'),
  FAIcons(FontAwesomeIcons.etsy, 'etsy'),
  FAIcons(FontAwesomeIcons.euroSign, 'euroSign'),
  FAIcons(FontAwesomeIcons.exchangeAlt, 'exchangeAlt'),
  FAIcons(FontAwesomeIcons.exclamation, 'exclamation'),
  FAIcons(FontAwesomeIcons.exclamationCircle, 'exclamationCircle'),
  FAIcons(FontAwesomeIcons.exclamationTriangle, 'exclamationTriangle'),
  FAIcons(FontAwesomeIcons.expand, 'expand'),
  FAIcons(FontAwesomeIcons.expandArrowsAlt, 'expandArrowsAlt'),
  FAIcons(FontAwesomeIcons.expeditedssl, 'expeditedssl'),
  FAIcons(FontAwesomeIcons.externalLinkAlt, 'externalLinkAlt'),
  FAIcons(FontAwesomeIcons.externalLinkSquareAlt, 'externalLinkSquareAlt'),
  FAIcons(FontAwesomeIcons.eye, 'eye'),
  FAIcons(FontAwesomeIcons.solidEye, 'solidEye'),
  FAIcons(FontAwesomeIcons.eyeDropper, 'eyeDropper'),
  FAIcons(FontAwesomeIcons.eyeSlash, 'eyeSlash'),
  FAIcons(FontAwesomeIcons.solidEyeSlash, 'solidEyeSlash'),
  FAIcons(FontAwesomeIcons.facebook, 'facebook'),
  FAIcons(FontAwesomeIcons.facebookF, 'facebookF'),
  FAIcons(FontAwesomeIcons.facebookMessenger, 'facebookMessenger'),
  FAIcons(FontAwesomeIcons.facebookSquare, 'facebookSquare'),
  FAIcons(FontAwesomeIcons.fantasyFlightGames, 'fantasyFlightGames'),
  FAIcons(FontAwesomeIcons.fastBackward, 'fastBackward'),
  FAIcons(FontAwesomeIcons.fastForward, 'fastForward'),
  FAIcons(FontAwesomeIcons.fax, 'fax'),
  FAIcons(FontAwesomeIcons.feather, 'feather'),
  FAIcons(FontAwesomeIcons.featherAlt, 'featherAlt'),
  FAIcons(FontAwesomeIcons.fedex, 'fedex'),
  FAIcons(FontAwesomeIcons.fedora, 'fedora'),
  FAIcons(FontAwesomeIcons.female, 'female'),
  FAIcons(FontAwesomeIcons.fighterJet, 'fighterJet'),
  FAIcons(FontAwesomeIcons.figma, 'figma'),
  FAIcons(FontAwesomeIcons.file, 'file'),
  FAIcons(FontAwesomeIcons.solidFile, 'solidFile'),
  FAIcons(FontAwesomeIcons.fileAlt, 'fileAlt'),
  FAIcons(FontAwesomeIcons.solidFileAlt, 'solidFileAlt'),
  FAIcons(FontAwesomeIcons.fileArchive, 'fileArchive'),
  FAIcons(FontAwesomeIcons.solidFileArchive, 'solidFileArchive'),
  FAIcons(FontAwesomeIcons.fileAudio, 'fileAudio'),
  FAIcons(FontAwesomeIcons.solidFileAudio, 'solidFileAudio'),
  FAIcons(FontAwesomeIcons.fileCode, 'fileCode'),
  FAIcons(FontAwesomeIcons.solidFileCode, 'solidFileCode'),
  FAIcons(FontAwesomeIcons.fileContract, 'fileContract'),
  FAIcons(FontAwesomeIcons.fileCsv, 'fileCsv'),
  FAIcons(FontAwesomeIcons.fileDownload, 'fileDownload'),
  FAIcons(FontAwesomeIcons.fileExcel, 'fileExcel'),
  FAIcons(FontAwesomeIcons.solidFileExcel, 'solidFileExcel'),
  FAIcons(FontAwesomeIcons.fileExport, 'fileExport'),
  FAIcons(FontAwesomeIcons.fileImage, 'fileImage'),
  FAIcons(FontAwesomeIcons.solidFileImage, 'solidFileImage'),
  FAIcons(FontAwesomeIcons.fileImport, 'fileImport'),
  FAIcons(FontAwesomeIcons.fileInvoice, 'fileInvoice'),
  FAIcons(FontAwesomeIcons.fileInvoiceDollar, 'fileInvoiceDollar'),
  FAIcons(FontAwesomeIcons.fileMedical, 'fileMedical'),
  FAIcons(FontAwesomeIcons.fileMedicalAlt, 'fileMedicalAlt'),
  FAIcons(FontAwesomeIcons.filePdf, 'filePdf'),
  FAIcons(FontAwesomeIcons.solidFilePdf, 'solidFilePdf'),
  FAIcons(FontAwesomeIcons.filePowerpoint, 'filePowerpoint'),
  FAIcons(FontAwesomeIcons.solidFilePowerpoint, 'solidFilePowerpoint'),
  FAIcons(FontAwesomeIcons.filePrescription, 'filePrescription'),
  FAIcons(FontAwesomeIcons.fileSignature, 'fileSignature'),
  FAIcons(FontAwesomeIcons.fileUpload, 'fileUpload'),
  FAIcons(FontAwesomeIcons.fileVideo, 'fileVideo'),
  FAIcons(FontAwesomeIcons.solidFileVideo, 'solidFileVideo'),
  FAIcons(FontAwesomeIcons.fileWord, 'fileWord'),
  FAIcons(FontAwesomeIcons.solidFileWord, 'solidFileWord'),
  FAIcons(FontAwesomeIcons.fill, 'fill'),
  FAIcons(FontAwesomeIcons.fillDrip, 'fillDrip'),
  FAIcons(FontAwesomeIcons.film, 'film'),
  FAIcons(FontAwesomeIcons.filter, 'filter'),
  FAIcons(FontAwesomeIcons.fingerprint, 'fingerprint'),
  FAIcons(FontAwesomeIcons.fire, 'fire'),
  FAIcons(FontAwesomeIcons.fireAlt, 'fireAlt'),
  FAIcons(FontAwesomeIcons.fireExtinguisher, 'fireExtinguisher'),
  FAIcons(FontAwesomeIcons.firefox, 'firefox'),
  FAIcons(FontAwesomeIcons.firstAid, 'firstAid'),
  FAIcons(FontAwesomeIcons.firstOrder, 'firstOrder'),
  FAIcons(FontAwesomeIcons.firstOrderAlt, 'firstOrderAlt'),
  FAIcons(FontAwesomeIcons.firstdraft, 'firstdraft'),
  FAIcons(FontAwesomeIcons.fish, 'fish'),
  FAIcons(FontAwesomeIcons.fistRaised, 'fistRaised'),
  FAIcons(FontAwesomeIcons.flag, 'flag'),
  FAIcons(FontAwesomeIcons.solidFlag, 'solidFlag'),
  FAIcons(FontAwesomeIcons.flagCheckered, 'flagCheckered'),
  FAIcons(FontAwesomeIcons.flagUsa, 'flagUsa'),
  FAIcons(FontAwesomeIcons.flask, 'flask'),
  FAIcons(FontAwesomeIcons.flickr, 'flickr'),
  FAIcons(FontAwesomeIcons.flipboard, 'flipboard'),
  FAIcons(FontAwesomeIcons.flushed, 'flushed'),
  FAIcons(FontAwesomeIcons.solidFlushed, 'solidFlushed'),
  FAIcons(FontAwesomeIcons.fly, 'fly'),
  FAIcons(FontAwesomeIcons.folder, 'folder'),
  FAIcons(FontAwesomeIcons.solidFolder, 'solidFolder'),
  FAIcons(FontAwesomeIcons.folderMinus, 'folderMinus'),
  FAIcons(FontAwesomeIcons.folderOpen, 'folderOpen'),
  FAIcons(FontAwesomeIcons.solidFolderOpen, 'solidFolderOpen'),
  FAIcons(FontAwesomeIcons.folderPlus, 'folderPlus'),
  FAIcons(FontAwesomeIcons.font, 'font'),
  FAIcons(FontAwesomeIcons.fontAwesome, 'fontAwesome'),
  FAIcons(FontAwesomeIcons.fontAwesomeAlt, 'fontAwesomeAlt'),
  FAIcons(FontAwesomeIcons.fontAwesomeFlag, 'fontAwesomeFlag'),
  FAIcons(FontAwesomeIcons.fontAwesomeLogoFull, 'fontAwesomeLogoFull'),
  FAIcons(
      FontAwesomeIcons.solidFontAwesomeLogoFull, 'solidFontAwesomeLogoFull'),
  FAIcons(
      FontAwesomeIcons.brandsFontAwesomeLogoFull, 'brandsFontAwesomeLogoFull'),
  FAIcons(FontAwesomeIcons.fonticons, 'fonticons'),
  FAIcons(FontAwesomeIcons.fonticonsFi, 'fonticonsFi'),
  FAIcons(FontAwesomeIcons.footballBall, 'footballBall'),
  FAIcons(FontAwesomeIcons.fortAwesome, 'fortAwesome'),
  FAIcons(FontAwesomeIcons.fortAwesomeAlt, 'fortAwesomeAlt'),
  FAIcons(FontAwesomeIcons.forumbee, 'forumbee'),
  FAIcons(FontAwesomeIcons.forward, 'forward'),
  FAIcons(FontAwesomeIcons.foursquare, 'foursquare'),
  FAIcons(FontAwesomeIcons.freeCodeCamp, 'freeCodeCamp'),
  FAIcons(FontAwesomeIcons.freebsd, 'freebsd'),
  FAIcons(FontAwesomeIcons.frog, 'frog'),
  FAIcons(FontAwesomeIcons.frown, 'frown'),
  FAIcons(FontAwesomeIcons.solidFrown, 'solidFrown'),
  FAIcons(FontAwesomeIcons.frownOpen, 'frownOpen'),
  FAIcons(FontAwesomeIcons.solidFrownOpen, 'solidFrownOpen'),
  FAIcons(FontAwesomeIcons.fulcrum, 'fulcrum'),
  FAIcons(FontAwesomeIcons.funnelDollar, 'funnelDollar'),
  FAIcons(FontAwesomeIcons.futbol, 'futbol'),
  FAIcons(FontAwesomeIcons.solidFutbol, 'solidFutbol'),
  FAIcons(FontAwesomeIcons.galacticRepublic, 'galacticRepublic'),
  FAIcons(FontAwesomeIcons.galacticSenate, 'galacticSenate'),
  FAIcons(FontAwesomeIcons.gamepad, 'gamepad'),
  FAIcons(FontAwesomeIcons.gasPump, 'gasPump'),
  FAIcons(FontAwesomeIcons.gavel, 'gavel'),
  FAIcons(FontAwesomeIcons.gem, 'gem'),
  FAIcons(FontAwesomeIcons.solidGem, 'solidGem'),
  FAIcons(FontAwesomeIcons.genderless, 'genderless'),
  FAIcons(FontAwesomeIcons.getPocket, 'getPocket'),
  FAIcons(FontAwesomeIcons.gg, 'gg'),
  FAIcons(FontAwesomeIcons.ggCircle, 'ggCircle'),
  FAIcons(FontAwesomeIcons.ghost, 'ghost'),
  FAIcons(FontAwesomeIcons.gift, 'gift'),
  FAIcons(FontAwesomeIcons.gifts, 'gifts'),
  FAIcons(FontAwesomeIcons.git, 'git'),
  FAIcons(FontAwesomeIcons.gitSquare, 'gitSquare'),
  FAIcons(FontAwesomeIcons.github, 'github'),
  FAIcons(FontAwesomeIcons.githubAlt, 'githubAlt'),
  FAIcons(FontAwesomeIcons.githubSquare, 'githubSquare'),
  FAIcons(FontAwesomeIcons.gitkraken, 'gitkraken'),
  FAIcons(FontAwesomeIcons.gitlab, 'gitlab'),
  FAIcons(FontAwesomeIcons.gitter, 'gitter'),
  FAIcons(FontAwesomeIcons.glassCheers, 'glassCheers'),
  FAIcons(FontAwesomeIcons.glassMartini, 'glassMartini'),
  FAIcons(FontAwesomeIcons.glassMartiniAlt, 'glassMartiniAlt'),
  FAIcons(FontAwesomeIcons.glassWhiskey, 'glassWhiskey'),
  FAIcons(FontAwesomeIcons.glasses, 'glasses'),
  FAIcons(FontAwesomeIcons.glide, 'glide'),
  FAIcons(FontAwesomeIcons.glideG, 'glideG'),
  FAIcons(FontAwesomeIcons.globe, 'globe'),
  FAIcons(FontAwesomeIcons.globeAfrica, 'globeAfrica'),
  FAIcons(FontAwesomeIcons.globeAmericas, 'globeAmericas'),
  FAIcons(FontAwesomeIcons.globeAsia, 'globeAsia'),
  FAIcons(FontAwesomeIcons.globeEurope, 'globeEurope'),
  FAIcons(FontAwesomeIcons.gofore, 'gofore'),
  FAIcons(FontAwesomeIcons.golfBall, 'golfBall'),
  FAIcons(FontAwesomeIcons.goodreads, 'goodreads'),
  FAIcons(FontAwesomeIcons.goodreadsG, 'goodreadsG'),
  FAIcons(FontAwesomeIcons.google, 'google'),
  FAIcons(FontAwesomeIcons.googleDrive, 'googleDrive'),
  FAIcons(FontAwesomeIcons.googlePlay, 'googlePlay'),
  FAIcons(FontAwesomeIcons.googlePlus, 'googlePlus'),
  FAIcons(FontAwesomeIcons.googlePlusG, 'googlePlusG'),
  FAIcons(FontAwesomeIcons.googlePlusSquare, 'googlePlusSquare'),
  FAIcons(FontAwesomeIcons.googleWallet, 'googleWallet'),
  FAIcons(FontAwesomeIcons.gopuram, 'gopuram'),
  FAIcons(FontAwesomeIcons.graduationCap, 'graduationCap'),
  FAIcons(FontAwesomeIcons.gratipay, 'gratipay'),
  FAIcons(FontAwesomeIcons.grav, 'grav'),
  FAIcons(FontAwesomeIcons.greaterThan, 'greaterThan'),
  FAIcons(FontAwesomeIcons.greaterThanEqual, 'greaterThanEqual'),
  FAIcons(FontAwesomeIcons.grimace, 'grimace'),
  FAIcons(FontAwesomeIcons.solidGrimace, 'solidGrimace'),
  FAIcons(FontAwesomeIcons.grin, 'grin'),
  FAIcons(FontAwesomeIcons.solidGrin, 'solidGrin'),
  FAIcons(FontAwesomeIcons.grinAlt, 'grinAlt'),
  FAIcons(FontAwesomeIcons.solidGrinAlt, 'solidGrinAlt'),
  FAIcons(FontAwesomeIcons.grinBeam, 'grinBeam'),
  FAIcons(FontAwesomeIcons.solidGrinBeam, 'solidGrinBeam'),
  FAIcons(FontAwesomeIcons.grinBeamSweat, 'grinBeamSweat'),
  FAIcons(FontAwesomeIcons.solidGrinBeamSweat, 'solidGrinBeamSweat'),
  FAIcons(FontAwesomeIcons.grinHearts, 'grinHearts'),
  FAIcons(FontAwesomeIcons.solidGrinHearts, 'solidGrinHearts'),
  FAIcons(FontAwesomeIcons.grinSquint, 'grinSquint'),
  FAIcons(FontAwesomeIcons.solidGrinSquint, 'solidGrinSquint'),
  FAIcons(FontAwesomeIcons.grinSquintTears, 'grinSquintTears'),
  FAIcons(FontAwesomeIcons.solidGrinSquintTears, 'solidGrinSquintTears'),
  FAIcons(FontAwesomeIcons.grinStars, 'grinStars'),
  FAIcons(FontAwesomeIcons.solidGrinStars, 'solidGrinStars'),
  FAIcons(FontAwesomeIcons.grinTears, 'grinTears'),
  FAIcons(FontAwesomeIcons.solidGrinTears, 'solidGrinTears'),
  FAIcons(FontAwesomeIcons.grinTongue, 'grinTongue'),
  FAIcons(FontAwesomeIcons.solidGrinTongue, 'solidGrinTongue'),
  FAIcons(FontAwesomeIcons.grinTongueSquint, 'grinTongueSquint'),
  FAIcons(FontAwesomeIcons.solidGrinTongueSquint, 'solidGrinTongueSquint'),
  FAIcons(FontAwesomeIcons.grinTongueWink, 'grinTongueWink'),
  FAIcons(FontAwesomeIcons.solidGrinTongueWink, 'solidGrinTongueWink'),
  FAIcons(FontAwesomeIcons.grinWink, 'grinWink'),
  FAIcons(FontAwesomeIcons.solidGrinWink, 'solidGrinWink'),
  FAIcons(FontAwesomeIcons.gripHorizontal, 'gripHorizontal'),
  FAIcons(FontAwesomeIcons.gripLines, 'gripLines'),
  FAIcons(FontAwesomeIcons.gripLinesVertical, 'gripLinesVertical'),
  FAIcons(FontAwesomeIcons.gripVertical, 'gripVertical'),
  FAIcons(FontAwesomeIcons.gripfire, 'gripfire'),
  FAIcons(FontAwesomeIcons.grunt, 'grunt'),
  FAIcons(FontAwesomeIcons.guitar, 'guitar'),
  FAIcons(FontAwesomeIcons.gulp, 'gulp'),
  FAIcons(FontAwesomeIcons.hSquare, 'hSquare'),
  FAIcons(FontAwesomeIcons.hackerNews, 'hackerNews'),
  FAIcons(FontAwesomeIcons.hackerNewsSquare, 'hackerNewsSquare'),
  FAIcons(FontAwesomeIcons.hackerrank, 'hackerrank'),
  FAIcons(FontAwesomeIcons.hamburger, 'hamburger'),
  FAIcons(FontAwesomeIcons.hammer, 'hammer'),
  FAIcons(FontAwesomeIcons.hamsa, 'hamsa'),
  FAIcons(FontAwesomeIcons.handHolding, 'handHolding'),
  FAIcons(FontAwesomeIcons.handHoldingHeart, 'handHoldingHeart'),
  FAIcons(FontAwesomeIcons.handHoldingUsd, 'handHoldingUsd'),
  FAIcons(FontAwesomeIcons.handLizard, 'handLizard'),
  FAIcons(FontAwesomeIcons.solidHandLizard, 'solidHandLizard'),
  FAIcons(FontAwesomeIcons.handMiddleFinger, 'handMiddleFinger'),
  FAIcons(FontAwesomeIcons.handPaper, 'handPaper'),
  FAIcons(FontAwesomeIcons.solidHandPaper, 'solidHandPaper'),
  FAIcons(FontAwesomeIcons.handPeace, 'handPeace'),
  FAIcons(FontAwesomeIcons.solidHandPeace, 'solidHandPeace'),
  FAIcons(FontAwesomeIcons.handPointDown, 'handPointDown'),
  FAIcons(FontAwesomeIcons.solidHandPointDown, 'solidHandPointDown'),
  FAIcons(FontAwesomeIcons.handPointLeft, 'handPointLeft'),
  FAIcons(FontAwesomeIcons.solidHandPointLeft, 'solidHandPointLeft'),
  FAIcons(FontAwesomeIcons.handPointRight, 'handPointRight'),
  FAIcons(FontAwesomeIcons.solidHandPointRight, 'solidHandPointRight'),
  FAIcons(FontAwesomeIcons.handPointUp, 'handPointUp'),
  FAIcons(FontAwesomeIcons.solidHandPointUp, 'solidHandPointUp'),
  FAIcons(FontAwesomeIcons.handPointer, 'handPointer'),
  FAIcons(FontAwesomeIcons.solidHandPointer, 'solidHandPointer'),
  FAIcons(FontAwesomeIcons.handRock, 'handRock'),
  FAIcons(FontAwesomeIcons.solidHandRock, 'solidHandRock'),
  FAIcons(FontAwesomeIcons.handScissors, 'handScissors'),
  FAIcons(FontAwesomeIcons.solidHandScissors, 'solidHandScissors'),
  FAIcons(FontAwesomeIcons.handSpock, 'handSpock'),
  FAIcons(FontAwesomeIcons.solidHandSpock, 'solidHandSpock'),
  FAIcons(FontAwesomeIcons.hands, 'hands'),
  FAIcons(FontAwesomeIcons.handsHelping, 'handsHelping'),
  FAIcons(FontAwesomeIcons.handshake, 'handshake'),
  FAIcons(FontAwesomeIcons.solidHandshake, 'solidHandshake'),
  FAIcons(FontAwesomeIcons.hanukiah, 'hanukiah'),
  FAIcons(FontAwesomeIcons.hardHat, 'hardHat'),
  FAIcons(FontAwesomeIcons.hashtag, 'hashtag'),
  FAIcons(FontAwesomeIcons.hatWizard, 'hatWizard'),
  FAIcons(FontAwesomeIcons.hdd, 'hdd'),
  FAIcons(FontAwesomeIcons.solidHdd, 'solidHdd'),
  FAIcons(FontAwesomeIcons.heading, 'heading'),
  FAIcons(FontAwesomeIcons.headphones, 'headphones'),
  FAIcons(FontAwesomeIcons.headphonesAlt, 'headphonesAlt'),
  FAIcons(FontAwesomeIcons.headset, 'headset'),
  FAIcons(FontAwesomeIcons.heart, 'heart'),
  FAIcons(FontAwesomeIcons.solidHeart, 'solidHeart'),
  FAIcons(FontAwesomeIcons.heartBroken, 'heartBroken'),
  FAIcons(FontAwesomeIcons.heartbeat, 'heartbeat'),
  FAIcons(FontAwesomeIcons.helicopter, 'helicopter'),
  FAIcons(FontAwesomeIcons.highlighter, 'highlighter'),
  FAIcons(FontAwesomeIcons.hiking, 'hiking'),
  FAIcons(FontAwesomeIcons.hippo, 'hippo'),
  FAIcons(FontAwesomeIcons.hips, 'hips'),
  FAIcons(FontAwesomeIcons.hireAHelper, 'hireAHelper'),
  FAIcons(FontAwesomeIcons.history, 'history'),
  FAIcons(FontAwesomeIcons.hockeyPuck, 'hockeyPuck'),
  FAIcons(FontAwesomeIcons.hollyBerry, 'hollyBerry'),
  FAIcons(FontAwesomeIcons.home, 'home'),
  FAIcons(FontAwesomeIcons.hooli, 'hooli'),
  FAIcons(FontAwesomeIcons.hornbill, 'hornbill'),
  FAIcons(FontAwesomeIcons.horse, 'horse'),
  FAIcons(FontAwesomeIcons.horseHead, 'horseHead'),
  FAIcons(FontAwesomeIcons.hospital, 'hospital'),
  FAIcons(FontAwesomeIcons.solidHospital, 'solidHospital'),
  FAIcons(FontAwesomeIcons.hospitalAlt, 'hospitalAlt'),
  FAIcons(FontAwesomeIcons.hospitalSymbol, 'hospitalSymbol'),
  FAIcons(FontAwesomeIcons.hotTub, 'hotTub'),
  FAIcons(FontAwesomeIcons.hotdog, 'hotdog'),
  FAIcons(FontAwesomeIcons.hotel, 'hotel'),
  FAIcons(FontAwesomeIcons.hotjar, 'hotjar'),
  FAIcons(FontAwesomeIcons.hourglass, 'hourglass'),
  FAIcons(FontAwesomeIcons.solidHourglass, 'solidHourglass'),
  FAIcons(FontAwesomeIcons.hourglassEnd, 'hourglassEnd'),
  FAIcons(FontAwesomeIcons.hourglassHalf, 'hourglassHalf'),
  FAIcons(FontAwesomeIcons.hourglassStart, 'hourglassStart'),
  FAIcons(FontAwesomeIcons.houseDamage, 'houseDamage'),
  FAIcons(FontAwesomeIcons.houzz, 'houzz'),
  FAIcons(FontAwesomeIcons.hryvnia, 'hryvnia'),
  FAIcons(FontAwesomeIcons.html5, 'html5'),
  FAIcons(FontAwesomeIcons.hubspot, 'hubspot'),
  FAIcons(FontAwesomeIcons.iCursor, 'iCursor'),
  FAIcons(FontAwesomeIcons.iceCream, 'iceCream'),
  FAIcons(FontAwesomeIcons.icicles, 'icicles'),
  FAIcons(FontAwesomeIcons.idBadge, 'idBadge'),
  FAIcons(FontAwesomeIcons.solidIdBadge, 'solidIdBadge'),
  FAIcons(FontAwesomeIcons.idCard, 'idCard'),
  FAIcons(FontAwesomeIcons.solidIdCard, 'solidIdCard'),
  FAIcons(FontAwesomeIcons.idCardAlt, 'idCardAlt'),
  FAIcons(FontAwesomeIcons.igloo, 'igloo'),
  FAIcons(FontAwesomeIcons.image, 'image'),
  FAIcons(FontAwesomeIcons.solidImage, 'solidImage'),
  FAIcons(FontAwesomeIcons.images, 'images'),
  FAIcons(FontAwesomeIcons.solidImages, 'solidImages'),
  FAIcons(FontAwesomeIcons.imdb, 'imdb'),
  FAIcons(FontAwesomeIcons.inbox, 'inbox'),
  FAIcons(FontAwesomeIcons.indent, 'indent'),
  FAIcons(FontAwesomeIcons.industry, 'industry'),
  FAIcons(FontAwesomeIcons.infinity, 'infinity'),
  FAIcons(FontAwesomeIcons.info, 'info'),
  FAIcons(FontAwesomeIcons.infoCircle, 'infoCircle'),
  FAIcons(FontAwesomeIcons.instagram, 'instagram'),
  FAIcons(FontAwesomeIcons.intercom, 'intercom'),
  FAIcons(FontAwesomeIcons.internetExplorer, 'internetExplorer'),
  FAIcons(FontAwesomeIcons.invision, 'invision'),
  FAIcons(FontAwesomeIcons.ioxhost, 'ioxhost'),
  FAIcons(FontAwesomeIcons.italic, 'italic'),
  FAIcons(FontAwesomeIcons.itunes, 'itunes'),
  FAIcons(FontAwesomeIcons.itunesNote, 'itunesNote'),
  FAIcons(FontAwesomeIcons.java, 'java'),
  FAIcons(FontAwesomeIcons.jedi, 'jedi'),
  FAIcons(FontAwesomeIcons.jediOrder, 'jediOrder'),
  FAIcons(FontAwesomeIcons.jenkins, 'jenkins'),
  FAIcons(FontAwesomeIcons.jira, 'jira'),
  FAIcons(FontAwesomeIcons.joget, 'joget'),
  FAIcons(FontAwesomeIcons.joint, 'joint'),
  FAIcons(FontAwesomeIcons.joomla, 'joomla'),
  FAIcons(FontAwesomeIcons.journalWhills, 'journalWhills'),
  FAIcons(FontAwesomeIcons.js, 'js'),
  FAIcons(FontAwesomeIcons.jsSquare, 'jsSquare'),
  FAIcons(FontAwesomeIcons.jsfiddle, 'jsfiddle'),
  FAIcons(FontAwesomeIcons.kaaba, 'kaaba'),
  FAIcons(FontAwesomeIcons.kaggle, 'kaggle'),
  FAIcons(FontAwesomeIcons.key, 'key'),
  FAIcons(FontAwesomeIcons.keybase, 'keybase'),
  FAIcons(FontAwesomeIcons.keyboard, 'keyboard'),
  FAIcons(FontAwesomeIcons.solidKeyboard, 'solidKeyboard'),
  FAIcons(FontAwesomeIcons.keycdn, 'keycdn'),
  FAIcons(FontAwesomeIcons.khanda, 'khanda'),
  FAIcons(FontAwesomeIcons.kickstarter, 'kickstarter'),
  FAIcons(FontAwesomeIcons.kickstarterK, 'kickstarterK'),
  FAIcons(FontAwesomeIcons.kiss, 'kiss'),
  FAIcons(FontAwesomeIcons.solidKiss, 'solidKiss'),
  FAIcons(FontAwesomeIcons.kissBeam, 'kissBeam'),
  FAIcons(FontAwesomeIcons.solidKissBeam, 'solidKissBeam'),
  FAIcons(FontAwesomeIcons.kissWinkHeart, 'kissWinkHeart'),
  FAIcons(FontAwesomeIcons.solidKissWinkHeart, 'solidKissWinkHeart'),
  FAIcons(FontAwesomeIcons.kiwiBird, 'kiwiBird'),
  FAIcons(FontAwesomeIcons.korvue, 'korvue'),
  FAIcons(FontAwesomeIcons.landmark, 'landmark'),
  FAIcons(FontAwesomeIcons.language, 'language'),
  FAIcons(FontAwesomeIcons.laptop, 'laptop'),
  FAIcons(FontAwesomeIcons.laptopCode, 'laptopCode'),
  FAIcons(FontAwesomeIcons.laptopMedical, 'laptopMedical'),
  FAIcons(FontAwesomeIcons.laravel, 'laravel'),
  FAIcons(FontAwesomeIcons.lastfm, 'lastfm'),
  FAIcons(FontAwesomeIcons.lastfmSquare, 'lastfmSquare'),
  FAIcons(FontAwesomeIcons.laugh, 'laugh'),
  FAIcons(FontAwesomeIcons.solidLaugh, 'solidLaugh'),
  FAIcons(FontAwesomeIcons.laughBeam, 'laughBeam'),
  FAIcons(FontAwesomeIcons.solidLaughBeam, 'solidLaughBeam'),
  FAIcons(FontAwesomeIcons.laughSquint, 'laughSquint'),
  FAIcons(FontAwesomeIcons.solidLaughSquint, 'solidLaughSquint'),
  FAIcons(FontAwesomeIcons.laughWink, 'laughWink'),
  FAIcons(FontAwesomeIcons.solidLaughWink, 'solidLaughWink'),
  FAIcons(FontAwesomeIcons.layerGroup, 'layerGroup'),
  FAIcons(FontAwesomeIcons.leaf, 'leaf'),
  FAIcons(FontAwesomeIcons.leanpub, 'leanpub'),
  FAIcons(FontAwesomeIcons.lemon, 'lemon'),
  FAIcons(FontAwesomeIcons.solidLemon, 'solidLemon'),
  FAIcons(FontAwesomeIcons.less, 'less'),
  FAIcons(FontAwesomeIcons.lessThan, 'lessThan'),
  FAIcons(FontAwesomeIcons.lessThanEqual, 'lessThanEqual'),
  FAIcons(FontAwesomeIcons.levelDownAlt, 'levelDownAlt'),
  FAIcons(FontAwesomeIcons.levelUpAlt, 'levelUpAlt'),
  FAIcons(FontAwesomeIcons.lifeRing, 'lifeRing'),
  FAIcons(FontAwesomeIcons.solidLifeRing, 'solidLifeRing'),
  FAIcons(FontAwesomeIcons.lightbulb, 'lightbulb'),
  FAIcons(FontAwesomeIcons.solidLightbulb, 'solidLightbulb'),
  FAIcons(FontAwesomeIcons.line, 'line'),
  FAIcons(FontAwesomeIcons.link, 'link'),
  FAIcons(FontAwesomeIcons.linkedin, 'linkedin'),
  FAIcons(FontAwesomeIcons.linkedinIn, 'linkedinIn'),
  FAIcons(FontAwesomeIcons.linode, 'linode'),
  FAIcons(FontAwesomeIcons.linux, 'linux'),
  FAIcons(FontAwesomeIcons.liraSign, 'liraSign'),
  FAIcons(FontAwesomeIcons.list, 'list'),
  FAIcons(FontAwesomeIcons.listAlt, 'listAlt'),
  FAIcons(FontAwesomeIcons.solidListAlt, 'solidListAlt'),
  FAIcons(FontAwesomeIcons.listOl, 'listOl'),
  FAIcons(FontAwesomeIcons.listUl, 'listUl'),
  FAIcons(FontAwesomeIcons.locationArrow, 'locationArrow'),
  FAIcons(FontAwesomeIcons.lock, 'lock'),
  FAIcons(FontAwesomeIcons.lockOpen, 'lockOpen'),
  FAIcons(FontAwesomeIcons.longArrowAltDown, 'longArrowAltDown'),
  FAIcons(FontAwesomeIcons.longArrowAltLeft, 'longArrowAltLeft'),
  FAIcons(FontAwesomeIcons.longArrowAltRight, 'longArrowAltRight'),
  FAIcons(FontAwesomeIcons.longArrowAltUp, 'longArrowAltUp'),
  FAIcons(FontAwesomeIcons.lowVision, 'lowVision'),
  FAIcons(FontAwesomeIcons.luggageCart, 'luggageCart'),
  FAIcons(FontAwesomeIcons.lyft, 'lyft'),
  FAIcons(FontAwesomeIcons.magento, 'magento'),
  FAIcons(FontAwesomeIcons.magic, 'magic'),
  FAIcons(FontAwesomeIcons.magnet, 'magnet'),
  FAIcons(FontAwesomeIcons.mailBulk, 'mailBulk'),
  FAIcons(FontAwesomeIcons.mailchimp, 'mailchimp'),
  FAIcons(FontAwesomeIcons.male, 'male'),
  FAIcons(FontAwesomeIcons.mandalorian, 'mandalorian'),
  FAIcons(FontAwesomeIcons.map, 'map'),
  FAIcons(FontAwesomeIcons.solidMap, 'solidMap'),
  FAIcons(FontAwesomeIcons.mapMarked, 'mapMarked'),
  FAIcons(FontAwesomeIcons.mapMarkedAlt, 'mapMarkedAlt'),
  FAIcons(FontAwesomeIcons.mapMarker, 'mapMarker'),
  FAIcons(FontAwesomeIcons.mapMarkerAlt, 'mapMarkerAlt'),
  FAIcons(FontAwesomeIcons.mapPin, 'mapPin'),
  FAIcons(FontAwesomeIcons.mapSigns, 'mapSigns'),
  FAIcons(FontAwesomeIcons.markdown, 'markdown'),
  FAIcons(FontAwesomeIcons.marker, 'marker'),
  FAIcons(FontAwesomeIcons.mars, 'mars'),
  FAIcons(FontAwesomeIcons.marsDouble, 'marsDouble'),
  FAIcons(FontAwesomeIcons.marsStroke, 'marsStroke'),
  FAIcons(FontAwesomeIcons.marsStrokeH, 'marsStrokeH'),
  FAIcons(FontAwesomeIcons.marsStrokeV, 'marsStrokeV'),
  FAIcons(FontAwesomeIcons.mask, 'mask'),
  FAIcons(FontAwesomeIcons.mastodon, 'mastodon'),
  FAIcons(FontAwesomeIcons.maxcdn, 'maxcdn'),
  FAIcons(FontAwesomeIcons.medal, 'medal'),
  FAIcons(FontAwesomeIcons.medapps, 'medapps'),
  FAIcons(FontAwesomeIcons.medium, 'medium'),
  FAIcons(FontAwesomeIcons.mediumM, 'mediumM'),
  FAIcons(FontAwesomeIcons.medkit, 'medkit'),
  FAIcons(FontAwesomeIcons.medrt, 'medrt'),
  FAIcons(FontAwesomeIcons.meetup, 'meetup'),
  FAIcons(FontAwesomeIcons.megaport, 'megaport'),
  FAIcons(FontAwesomeIcons.meh, 'meh'),
  FAIcons(FontAwesomeIcons.solidMeh, 'solidMeh'),
  FAIcons(FontAwesomeIcons.mehBlank, 'mehBlank'),
  FAIcons(FontAwesomeIcons.solidMehBlank, 'solidMehBlank'),
  FAIcons(FontAwesomeIcons.mehRollingEyes, 'mehRollingEyes'),
  FAIcons(FontAwesomeIcons.solidMehRollingEyes, 'solidMehRollingEyes'),
  FAIcons(FontAwesomeIcons.memory, 'memory'),
  FAIcons(FontAwesomeIcons.mendeley, 'mendeley'),
  FAIcons(FontAwesomeIcons.menorah, 'menorah'),
  FAIcons(FontAwesomeIcons.mercury, 'mercury'),
  FAIcons(FontAwesomeIcons.meteor, 'meteor'),
  FAIcons(FontAwesomeIcons.microchip, 'microchip'),
  FAIcons(FontAwesomeIcons.microphone, 'microphone'),
  FAIcons(FontAwesomeIcons.microphoneAlt, 'microphoneAlt'),
  FAIcons(FontAwesomeIcons.microphoneAltSlash, 'microphoneAltSlash'),
  FAIcons(FontAwesomeIcons.microphoneSlash, 'microphoneSlash'),
  FAIcons(FontAwesomeIcons.microscope, 'microscope'),
  FAIcons(FontAwesomeIcons.microsoft, 'microsoft'),
  FAIcons(FontAwesomeIcons.minus, 'minus'),
  FAIcons(FontAwesomeIcons.minusCircle, 'minusCircle'),
  FAIcons(FontAwesomeIcons.minusSquare, 'minusSquare'),
  FAIcons(FontAwesomeIcons.solidMinusSquare, 'solidMinusSquare'),
  FAIcons(FontAwesomeIcons.mitten, 'mitten'),
  FAIcons(FontAwesomeIcons.mix, 'mix'),
  FAIcons(FontAwesomeIcons.mixcloud, 'mixcloud'),
  FAIcons(FontAwesomeIcons.mizuni, 'mizuni'),
  FAIcons(FontAwesomeIcons.mobile, 'mobile'),
  FAIcons(FontAwesomeIcons.mobileAlt, 'mobileAlt'),
  FAIcons(FontAwesomeIcons.modx, 'modx'),
  FAIcons(FontAwesomeIcons.monero, 'monero'),
  FAIcons(FontAwesomeIcons.moneyBill, 'moneyBill'),
  FAIcons(FontAwesomeIcons.moneyBillAlt, 'moneyBillAlt'),
  FAIcons(FontAwesomeIcons.solidMoneyBillAlt, 'solidMoneyBillAlt'),
  FAIcons(FontAwesomeIcons.moneyBillWave, 'moneyBillWave'),
  FAIcons(FontAwesomeIcons.moneyBillWaveAlt, 'moneyBillWaveAlt'),
  FAIcons(FontAwesomeIcons.moneyCheck, 'moneyCheck'),
  FAIcons(FontAwesomeIcons.moneyCheckAlt, 'moneyCheckAlt'),
  FAIcons(FontAwesomeIcons.monument, 'monument'),
  FAIcons(FontAwesomeIcons.moon, 'moon'),
  FAIcons(FontAwesomeIcons.solidMoon, 'solidMoon'),
  FAIcons(FontAwesomeIcons.mortarPestle, 'mortarPestle'),
  FAIcons(FontAwesomeIcons.mosque, 'mosque'),
  FAIcons(FontAwesomeIcons.motorcycle, 'motorcycle'),
  FAIcons(FontAwesomeIcons.mountain, 'mountain'),
  FAIcons(FontAwesomeIcons.mousePointer, 'mousePointer'),
  FAIcons(FontAwesomeIcons.mugHot, 'mugHot'),
  FAIcons(FontAwesomeIcons.music, 'music'),
  FAIcons(FontAwesomeIcons.napster, 'napster'),
  FAIcons(FontAwesomeIcons.neos, 'neos'),
  FAIcons(FontAwesomeIcons.networkWired, 'networkWired'),
  FAIcons(FontAwesomeIcons.neuter, 'neuter'),
  FAIcons(FontAwesomeIcons.newspaper, 'newspaper'),
  FAIcons(FontAwesomeIcons.solidNewspaper, 'solidNewspaper'),
  FAIcons(FontAwesomeIcons.nimblr, 'nimblr'),
  //FAIcons(FontAwesomeIcons.nintendoSwitch, 'nintendoSwitch'),
  FAIcons(FontAwesomeIcons.node, 'node'),
  FAIcons(FontAwesomeIcons.nodeJs, 'nodeJs'),
  FAIcons(FontAwesomeIcons.notEqual, 'notEqual'),
  FAIcons(FontAwesomeIcons.notesMedical, 'notesMedical'),
  FAIcons(FontAwesomeIcons.npm, 'npm'),
  FAIcons(FontAwesomeIcons.ns8, 'ns8'),
  FAIcons(FontAwesomeIcons.nutritionix, 'nutritionix'),
  FAIcons(FontAwesomeIcons.objectGroup, 'objectGroup'),
  FAIcons(FontAwesomeIcons.solidObjectGroup, 'solidObjectGroup'),
  FAIcons(FontAwesomeIcons.objectUngroup, 'objectUngroup'),
  FAIcons(FontAwesomeIcons.solidObjectUngroup, 'solidObjectUngroup'),
  FAIcons(FontAwesomeIcons.odnoklassniki, 'odnoklassniki'),
  FAIcons(FontAwesomeIcons.odnoklassnikiSquare, 'odnoklassnikiSquare'),
  FAIcons(FontAwesomeIcons.oilCan, 'oilCan'),
  FAIcons(FontAwesomeIcons.oldRepublic, 'oldRepublic'),
  FAIcons(FontAwesomeIcons.om, 'om'),
  FAIcons(FontAwesomeIcons.opencart, 'opencart'),
  FAIcons(FontAwesomeIcons.openid, 'openid'),
  FAIcons(FontAwesomeIcons.opera, 'opera'),
  FAIcons(FontAwesomeIcons.optinMonster, 'optinMonster'),
  FAIcons(FontAwesomeIcons.osi, 'osi'),
  FAIcons(FontAwesomeIcons.otter, 'otter'),
  FAIcons(FontAwesomeIcons.outdent, 'outdent'),
  FAIcons(FontAwesomeIcons.page4, 'page4'),
  FAIcons(FontAwesomeIcons.pagelines, 'pagelines'),
  FAIcons(FontAwesomeIcons.pager, 'pager'),
  FAIcons(FontAwesomeIcons.paintBrush, 'paintBrush'),
  FAIcons(FontAwesomeIcons.paintRoller, 'paintRoller'),
  FAIcons(FontAwesomeIcons.palette, 'palette'),
  FAIcons(FontAwesomeIcons.palfed, 'palfed'),
  FAIcons(FontAwesomeIcons.pallet, 'pallet'),
  FAIcons(FontAwesomeIcons.paperPlane, 'paperPlane'),
  FAIcons(FontAwesomeIcons.solidPaperPlane, 'solidPaperPlane'),
  FAIcons(FontAwesomeIcons.paperclip, 'paperclip'),
  FAIcons(FontAwesomeIcons.parachuteBox, 'parachuteBox'),
  FAIcons(FontAwesomeIcons.paragraph, 'paragraph'),
  FAIcons(FontAwesomeIcons.parking, 'parking'),
  FAIcons(FontAwesomeIcons.passport, 'passport'),
  FAIcons(FontAwesomeIcons.pastafarianism, 'pastafarianism'),
  FAIcons(FontAwesomeIcons.paste, 'paste'),
  FAIcons(FontAwesomeIcons.patreon, 'patreon'),
  FAIcons(FontAwesomeIcons.pause, 'pause'),
  FAIcons(FontAwesomeIcons.pauseCircle, 'pauseCircle'),
  FAIcons(FontAwesomeIcons.solidPauseCircle, 'solidPauseCircle'),
  FAIcons(FontAwesomeIcons.paw, 'paw'),
  FAIcons(FontAwesomeIcons.paypal, 'paypal'),
  FAIcons(FontAwesomeIcons.peace, 'peace'),
  FAIcons(FontAwesomeIcons.pen, 'pen'),
  FAIcons(FontAwesomeIcons.penAlt, 'penAlt'),
  FAIcons(FontAwesomeIcons.penFancy, 'penFancy'),
  FAIcons(FontAwesomeIcons.penNib, 'penNib'),
  FAIcons(FontAwesomeIcons.penSquare, 'penSquare'),
  FAIcons(FontAwesomeIcons.pencilAlt, 'pencilAlt'),
  FAIcons(FontAwesomeIcons.pencilRuler, 'pencilRuler'),
  FAIcons(FontAwesomeIcons.pennyArcade, 'pennyArcade'),
  FAIcons(FontAwesomeIcons.peopleCarry, 'peopleCarry'),
  FAIcons(FontAwesomeIcons.pepperHot, 'pepperHot'),
  FAIcons(FontAwesomeIcons.percent, 'percent'),
  FAIcons(FontAwesomeIcons.percentage, 'percentage'),
  FAIcons(FontAwesomeIcons.periscope, 'periscope'),
  FAIcons(FontAwesomeIcons.personBooth, 'personBooth'),
  FAIcons(FontAwesomeIcons.phabricator, 'phabricator'),
  FAIcons(FontAwesomeIcons.phoenixFramework, 'phoenixFramework'),
  FAIcons(FontAwesomeIcons.phoenixSquadron, 'phoenixSquadron'),
  FAIcons(FontAwesomeIcons.phone, 'phone'),
  FAIcons(FontAwesomeIcons.phoneSlash, 'phoneSlash'),
  FAIcons(FontAwesomeIcons.phoneSquare, 'phoneSquare'),
  FAIcons(FontAwesomeIcons.phoneVolume, 'phoneVolume'),
  FAIcons(FontAwesomeIcons.php, 'php'),
  FAIcons(FontAwesomeIcons.piedPiper, 'piedPiper'),
  FAIcons(FontAwesomeIcons.piedPiperAlt, 'piedPiperAlt'),
  FAIcons(FontAwesomeIcons.piedPiperHat, 'piedPiperHat'),
  FAIcons(FontAwesomeIcons.piedPiperPp, 'piedPiperPp'),
  FAIcons(FontAwesomeIcons.piggyBank, 'piggyBank'),
  FAIcons(FontAwesomeIcons.pills, 'pills'),
  FAIcons(FontAwesomeIcons.pinterest, 'pinterest'),
  FAIcons(FontAwesomeIcons.pinterestP, 'pinterestP'),
  FAIcons(FontAwesomeIcons.pinterestSquare, 'pinterestSquare'),
  FAIcons(FontAwesomeIcons.pizzaSlice, 'pizzaSlice'),
  FAIcons(FontAwesomeIcons.placeOfWorship, 'placeOfWorship'),
  FAIcons(FontAwesomeIcons.plane, 'plane'),
  FAIcons(FontAwesomeIcons.planeArrival, 'planeArrival'),
  FAIcons(FontAwesomeIcons.planeDeparture, 'planeDeparture'),
  FAIcons(FontAwesomeIcons.play, 'play'),
  FAIcons(FontAwesomeIcons.playCircle, 'playCircle'),
  FAIcons(FontAwesomeIcons.solidPlayCircle, 'solidPlayCircle'),
  FAIcons(FontAwesomeIcons.playstation, 'playstation'),
  FAIcons(FontAwesomeIcons.plug, 'plug'),
  FAIcons(FontAwesomeIcons.plus, 'plus'),
  FAIcons(FontAwesomeIcons.plusCircle, 'plusCircle'),
  FAIcons(FontAwesomeIcons.plusSquare, 'plusSquare'),
  FAIcons(FontAwesomeIcons.solidPlusSquare, 'solidPlusSquare'),
  FAIcons(FontAwesomeIcons.podcast, 'podcast'),
  FAIcons(FontAwesomeIcons.poll, 'poll'),
  FAIcons(FontAwesomeIcons.pollH, 'pollH'),
  FAIcons(FontAwesomeIcons.poo, 'poo'),
  FAIcons(FontAwesomeIcons.pooStorm, 'pooStorm'),
  FAIcons(FontAwesomeIcons.poop, 'poop'),
  FAIcons(FontAwesomeIcons.portrait, 'portrait'),
  FAIcons(FontAwesomeIcons.poundSign, 'poundSign'),
  FAIcons(FontAwesomeIcons.powerOff, 'powerOff'),
  FAIcons(FontAwesomeIcons.pray, 'pray'),
  FAIcons(FontAwesomeIcons.prayingHands, 'prayingHands'),
  FAIcons(FontAwesomeIcons.prescription, 'prescription'),
  FAIcons(FontAwesomeIcons.prescriptionBottle, 'prescriptionBottle'),
  FAIcons(FontAwesomeIcons.prescriptionBottleAlt, 'prescriptionBottleAlt'),
  FAIcons(FontAwesomeIcons.print, 'print'),
  FAIcons(FontAwesomeIcons.procedures, 'procedures'),
  FAIcons(FontAwesomeIcons.productHunt, 'productHunt'),
  FAIcons(FontAwesomeIcons.projectDiagram, 'projectDiagram'),
  FAIcons(FontAwesomeIcons.pushed, 'pushed'),
  FAIcons(FontAwesomeIcons.puzzlePiece, 'puzzlePiece'),
  FAIcons(FontAwesomeIcons.python, 'python'),
  FAIcons(FontAwesomeIcons.qq, 'qq'),
  FAIcons(FontAwesomeIcons.qrcode, 'qrcode'),
  FAIcons(FontAwesomeIcons.question, 'question'),
  FAIcons(FontAwesomeIcons.questionCircle, 'questionCircle'),
  FAIcons(FontAwesomeIcons.solidQuestionCircle, 'solidQuestionCircle'),
  FAIcons(FontAwesomeIcons.quidditch, 'quidditch'),
  FAIcons(FontAwesomeIcons.quinscape, 'quinscape'),
  FAIcons(FontAwesomeIcons.quora, 'quora'),
  FAIcons(FontAwesomeIcons.quoteLeft, 'quoteLeft'),
  FAIcons(FontAwesomeIcons.quoteRight, 'quoteRight'),
  FAIcons(FontAwesomeIcons.quran, 'quran'),
  FAIcons(FontAwesomeIcons.rProject, 'rProject'),
  FAIcons(FontAwesomeIcons.radiation, 'radiation'),
  FAIcons(FontAwesomeIcons.radiationAlt, 'radiationAlt'),
  FAIcons(FontAwesomeIcons.rainbow, 'rainbow'),
  FAIcons(FontAwesomeIcons.random, 'random'),
  FAIcons(FontAwesomeIcons.raspberryPi, 'raspberryPi'),
  FAIcons(FontAwesomeIcons.ravelry, 'ravelry'),
  FAIcons(FontAwesomeIcons.react, 'react'),
  FAIcons(FontAwesomeIcons.reacteurope, 'reacteurope'),
  FAIcons(FontAwesomeIcons.readme, 'readme'),
  FAIcons(FontAwesomeIcons.rebel, 'rebel'),
  FAIcons(FontAwesomeIcons.receipt, 'receipt'),
  FAIcons(FontAwesomeIcons.recycle, 'recycle'),
  FAIcons(FontAwesomeIcons.redRiver, 'redRiver'),
  FAIcons(FontAwesomeIcons.reddit, 'reddit'),
  FAIcons(FontAwesomeIcons.redditAlien, 'redditAlien'),
  FAIcons(FontAwesomeIcons.redditSquare, 'redditSquare'),
  FAIcons(FontAwesomeIcons.redhat, 'redhat'),
  FAIcons(FontAwesomeIcons.redo, 'redo'),
  FAIcons(FontAwesomeIcons.redoAlt, 'redoAlt'),
  FAIcons(FontAwesomeIcons.registered, 'registered'),
  FAIcons(FontAwesomeIcons.solidRegistered, 'solidRegistered'),
  FAIcons(FontAwesomeIcons.renren, 'renren'),
  FAIcons(FontAwesomeIcons.reply, 'reply'),
  FAIcons(FontAwesomeIcons.replyAll, 'replyAll'),
  FAIcons(FontAwesomeIcons.replyd, 'replyd'),
  FAIcons(FontAwesomeIcons.republican, 'republican'),
  FAIcons(FontAwesomeIcons.researchgate, 'researchgate'),
  FAIcons(FontAwesomeIcons.resolving, 'resolving'),
  FAIcons(FontAwesomeIcons.restroom, 'restroom'),
  FAIcons(FontAwesomeIcons.retweet, 'retweet'),
  FAIcons(FontAwesomeIcons.rev, 'rev'),
  FAIcons(FontAwesomeIcons.ribbon, 'ribbon'),
  FAIcons(FontAwesomeIcons.ring, 'ring'),
  FAIcons(FontAwesomeIcons.road, 'road'),
  FAIcons(FontAwesomeIcons.robot, 'robot'),
  FAIcons(FontAwesomeIcons.rocket, 'rocket'),
  FAIcons(FontAwesomeIcons.rocketchat, 'rocketchat'),
  FAIcons(FontAwesomeIcons.rockrms, 'rockrms'),
  FAIcons(FontAwesomeIcons.route, 'route'),
  FAIcons(FontAwesomeIcons.rss, 'rss'),
  FAIcons(FontAwesomeIcons.rssSquare, 'rssSquare'),
  FAIcons(FontAwesomeIcons.rubleSign, 'rubleSign'),
  FAIcons(FontAwesomeIcons.ruler, 'ruler'),
  FAIcons(FontAwesomeIcons.rulerCombined, 'rulerCombined'),
  FAIcons(FontAwesomeIcons.rulerHorizontal, 'rulerHorizontal'),
  FAIcons(FontAwesomeIcons.rulerVertical, 'rulerVertical'),
  FAIcons(FontAwesomeIcons.running, 'running'),
  FAIcons(FontAwesomeIcons.rupeeSign, 'rupeeSign'),
  FAIcons(FontAwesomeIcons.sadCry, 'sadCry'),
  FAIcons(FontAwesomeIcons.solidSadCry, 'solidSadCry'),
  FAIcons(FontAwesomeIcons.sadTear, 'sadTear'),
  FAIcons(FontAwesomeIcons.solidSadTear, 'solidSadTear'),
  FAIcons(FontAwesomeIcons.safari, 'safari'),
  FAIcons(FontAwesomeIcons.sass, 'sass'),
  FAIcons(FontAwesomeIcons.satellite, 'satellite'),
  FAIcons(FontAwesomeIcons.satelliteDish, 'satelliteDish'),
  FAIcons(FontAwesomeIcons.save, 'save'),
  FAIcons(FontAwesomeIcons.solidSave, 'solidSave'),
  FAIcons(FontAwesomeIcons.schlix, 'schlix'),
  FAIcons(FontAwesomeIcons.school, 'school'),
  FAIcons(FontAwesomeIcons.screwdriver, 'screwdriver'),
  FAIcons(FontAwesomeIcons.scribd, 'scribd'),
  FAIcons(FontAwesomeIcons.scroll, 'scroll'),
  FAIcons(FontAwesomeIcons.sdCard, 'sdCard'),
  FAIcons(FontAwesomeIcons.search, 'search'),
  FAIcons(FontAwesomeIcons.searchDollar, 'searchDollar'),
  FAIcons(FontAwesomeIcons.searchLocation, 'searchLocation'),
  FAIcons(FontAwesomeIcons.searchMinus, 'searchMinus'),
  FAIcons(FontAwesomeIcons.searchPlus, 'searchPlus'),
  FAIcons(FontAwesomeIcons.searchengin, 'searchengin'),
  FAIcons(FontAwesomeIcons.seedling, 'seedling'),
  FAIcons(FontAwesomeIcons.sellcast, 'sellcast'),
  FAIcons(FontAwesomeIcons.sellsy, 'sellsy'),
  FAIcons(FontAwesomeIcons.server, 'server'),
  FAIcons(FontAwesomeIcons.servicestack, 'servicestack'),
  FAIcons(FontAwesomeIcons.shapes, 'shapes'),
  FAIcons(FontAwesomeIcons.share, 'share'),
  FAIcons(FontAwesomeIcons.shareAlt, 'shareAlt'),
  FAIcons(FontAwesomeIcons.shareAltSquare, 'shareAltSquare'),
  FAIcons(FontAwesomeIcons.shareSquare, 'shareSquare'),
  FAIcons(FontAwesomeIcons.solidShareSquare, 'solidShareSquare'),
  FAIcons(FontAwesomeIcons.shekelSign, 'shekelSign'),
  FAIcons(FontAwesomeIcons.shieldAlt, 'shieldAlt'),
  FAIcons(FontAwesomeIcons.ship, 'ship'),
  FAIcons(FontAwesomeIcons.shippingFast, 'shippingFast'),
  FAIcons(FontAwesomeIcons.shirtsinbulk, 'shirtsinbulk'),
  FAIcons(FontAwesomeIcons.shoePrints, 'shoePrints'),
  FAIcons(FontAwesomeIcons.shoppingBag, 'shoppingBag'),
  FAIcons(FontAwesomeIcons.shoppingBasket, 'shoppingBasket'),
  FAIcons(FontAwesomeIcons.shoppingCart, 'shoppingCart'),
  FAIcons(FontAwesomeIcons.shopware, 'shopware'),
  FAIcons(FontAwesomeIcons.shower, 'shower'),
  FAIcons(FontAwesomeIcons.shuttleVan, 'shuttleVan'),
  FAIcons(FontAwesomeIcons.sign, 'sign'),
  FAIcons(FontAwesomeIcons.signInAlt, 'signInAlt'),
  FAIcons(FontAwesomeIcons.signLanguage, 'signLanguage'),
  FAIcons(FontAwesomeIcons.signOutAlt, 'signOutAlt'),
  FAIcons(FontAwesomeIcons.signal, 'signal'),
  FAIcons(FontAwesomeIcons.signature, 'signature'),
  FAIcons(FontAwesomeIcons.simCard, 'simCard'),
  FAIcons(FontAwesomeIcons.simplybuilt, 'simplybuilt'),
  FAIcons(FontAwesomeIcons.sistrix, 'sistrix'),
  FAIcons(FontAwesomeIcons.sitemap, 'sitemap'),
  FAIcons(FontAwesomeIcons.sith, 'sith'),
  FAIcons(FontAwesomeIcons.skating, 'skating'),
  FAIcons(FontAwesomeIcons.sketch, 'sketch'),
  FAIcons(FontAwesomeIcons.skiing, 'skiing'),
  FAIcons(FontAwesomeIcons.skiingNordic, 'skiingNordic'),
  FAIcons(FontAwesomeIcons.skull, 'skull'),
  FAIcons(FontAwesomeIcons.skullCrossbones, 'skullCrossbones'),
  FAIcons(FontAwesomeIcons.skyatlas, 'skyatlas'),
  FAIcons(FontAwesomeIcons.skype, 'skype'),
  FAIcons(FontAwesomeIcons.slack, 'slack'),
  FAIcons(FontAwesomeIcons.slackHash, 'slackHash'),
  FAIcons(FontAwesomeIcons.slash, 'slash'),
  FAIcons(FontAwesomeIcons.sleigh, 'sleigh'),
  FAIcons(FontAwesomeIcons.slidersH, 'slidersH'),
  FAIcons(FontAwesomeIcons.slideshare, 'slideshare'),
  FAIcons(FontAwesomeIcons.smile, 'smile'),
  FAIcons(FontAwesomeIcons.solidSmile, 'solidSmile'),
  FAIcons(FontAwesomeIcons.smileBeam, 'smileBeam'),
  FAIcons(FontAwesomeIcons.solidSmileBeam, 'solidSmileBeam'),
  FAIcons(FontAwesomeIcons.smileWink, 'smileWink'),
  FAIcons(FontAwesomeIcons.solidSmileWink, 'solidSmileWink'),
  FAIcons(FontAwesomeIcons.smog, 'smog'),
  FAIcons(FontAwesomeIcons.smoking, 'smoking'),
  FAIcons(FontAwesomeIcons.smokingBan, 'smokingBan'),
  FAIcons(FontAwesomeIcons.sms, 'sms'),
  FAIcons(FontAwesomeIcons.snapchat, 'snapchat'),
  FAIcons(FontAwesomeIcons.snapchatGhost, 'snapchatGhost'),
  FAIcons(FontAwesomeIcons.snapchatSquare, 'snapchatSquare'),
  FAIcons(FontAwesomeIcons.snowboarding, 'snowboarding'),
  FAIcons(FontAwesomeIcons.snowflake, 'snowflake'),
  FAIcons(FontAwesomeIcons.solidSnowflake, 'solidSnowflake'),
  FAIcons(FontAwesomeIcons.snowman, 'snowman'),
  FAIcons(FontAwesomeIcons.snowplow, 'snowplow'),
  FAIcons(FontAwesomeIcons.socks, 'socks'),
  FAIcons(FontAwesomeIcons.solarPanel, 'solarPanel'),
  FAIcons(FontAwesomeIcons.sort, 'sort'),
  FAIcons(FontAwesomeIcons.sortAlphaDown, 'sortAlphaDown'),
  FAIcons(FontAwesomeIcons.sortAlphaUp, 'sortAlphaUp'),
  FAIcons(FontAwesomeIcons.sortAmountDown, 'sortAmountDown'),
  FAIcons(FontAwesomeIcons.sortAmountUp, 'sortAmountUp'),
  FAIcons(FontAwesomeIcons.sortDown, 'sortDown'),
  FAIcons(FontAwesomeIcons.sortNumericDown, 'sortNumericDown'),
  FAIcons(FontAwesomeIcons.sortNumericUp, 'sortNumericUp'),
  FAIcons(FontAwesomeIcons.sortUp, 'sortUp'),
  FAIcons(FontAwesomeIcons.soundcloud, 'soundcloud'),
  FAIcons(FontAwesomeIcons.sourcetree, 'sourcetree'),
  FAIcons(FontAwesomeIcons.spa, 'spa'),
  FAIcons(FontAwesomeIcons.spaceShuttle, 'spaceShuttle'),
  FAIcons(FontAwesomeIcons.speakap, 'speakap'),
  FAIcons(FontAwesomeIcons.spider, 'spider'),
  FAIcons(FontAwesomeIcons.spinner, 'spinner'),
  FAIcons(FontAwesomeIcons.splotch, 'splotch'),
  FAIcons(FontAwesomeIcons.spotify, 'spotify'),
  FAIcons(FontAwesomeIcons.sprayCan, 'sprayCan'),
  FAIcons(FontAwesomeIcons.square, 'square'),
  FAIcons(FontAwesomeIcons.solidSquare, 'solidSquare'),
  FAIcons(FontAwesomeIcons.squareFull, 'squareFull'),
  FAIcons(FontAwesomeIcons.squareRootAlt, 'squareRootAlt'),
  FAIcons(FontAwesomeIcons.squarespace, 'squarespace'),
  FAIcons(FontAwesomeIcons.stackExchange, 'stackExchange'),
  FAIcons(FontAwesomeIcons.stackOverflow, 'stackOverflow'),
  FAIcons(FontAwesomeIcons.stamp, 'stamp'),
  FAIcons(FontAwesomeIcons.star, 'star'),
  FAIcons(FontAwesomeIcons.solidStar, 'solidStar'),
  FAIcons(FontAwesomeIcons.starAndCrescent, 'starAndCrescent'),
  FAIcons(FontAwesomeIcons.starHalf, 'starHalf'),
  FAIcons(FontAwesomeIcons.solidStarHalf, 'solidStarHalf'),
  FAIcons(FontAwesomeIcons.starHalfAlt, 'starHalfAlt'),
  FAIcons(FontAwesomeIcons.starOfDavid, 'starOfDavid'),
  FAIcons(FontAwesomeIcons.starOfLife, 'starOfLife'),
  FAIcons(FontAwesomeIcons.staylinked, 'staylinked'),
  FAIcons(FontAwesomeIcons.steam, 'steam'),
  FAIcons(FontAwesomeIcons.steamSquare, 'steamSquare'),
  FAIcons(FontAwesomeIcons.steamSymbol, 'steamSymbol'),
  FAIcons(FontAwesomeIcons.stepBackward, 'stepBackward'),
  FAIcons(FontAwesomeIcons.stepForward, 'stepForward'),
  FAIcons(FontAwesomeIcons.stethoscope, 'stethoscope'),
  FAIcons(FontAwesomeIcons.stickerMule, 'stickerMule'),
  FAIcons(FontAwesomeIcons.stickyNote, 'stickyNote'),
  FAIcons(FontAwesomeIcons.solidStickyNote, 'solidStickyNote'),
  FAIcons(FontAwesomeIcons.stop, 'stop'),
  FAIcons(FontAwesomeIcons.stopCircle, 'stopCircle'),
  FAIcons(FontAwesomeIcons.solidStopCircle, 'solidStopCircle'),
  FAIcons(FontAwesomeIcons.stopwatch, 'stopwatch'),
  FAIcons(FontAwesomeIcons.store, 'store'),
  FAIcons(FontAwesomeIcons.storeAlt, 'storeAlt'),
  FAIcons(FontAwesomeIcons.strava, 'strava'),
  FAIcons(FontAwesomeIcons.stream, 'stream'),
  FAIcons(FontAwesomeIcons.streetView, 'streetView'),
  FAIcons(FontAwesomeIcons.strikethrough, 'strikethrough'),
  FAIcons(FontAwesomeIcons.stripe, 'stripe'),
  FAIcons(FontAwesomeIcons.stripeS, 'stripeS'),
  FAIcons(FontAwesomeIcons.stroopwafel, 'stroopwafel'),
  FAIcons(FontAwesomeIcons.studiovinari, 'studiovinari'),
  FAIcons(FontAwesomeIcons.stumbleupon, 'stumbleupon'),
  FAIcons(FontAwesomeIcons.stumbleuponCircle, 'stumbleuponCircle'),
  FAIcons(FontAwesomeIcons.subscript, 'subscript'),
  FAIcons(FontAwesomeIcons.subway, 'subway'),
  FAIcons(FontAwesomeIcons.suitcase, 'suitcase'),
  FAIcons(FontAwesomeIcons.suitcaseRolling, 'suitcaseRolling'),
  FAIcons(FontAwesomeIcons.sun, 'sun'),
  FAIcons(FontAwesomeIcons.solidSun, 'solidSun'),
  FAIcons(FontAwesomeIcons.superpowers, 'superpowers'),
  FAIcons(FontAwesomeIcons.superscript, 'superscript'),
  FAIcons(FontAwesomeIcons.supple, 'supple'),
  FAIcons(FontAwesomeIcons.surprise, 'surprise'),
  FAIcons(FontAwesomeIcons.solidSurprise, 'solidSurprise'),
  FAIcons(FontAwesomeIcons.suse, 'suse'),
  FAIcons(FontAwesomeIcons.swatchbook, 'swatchbook'),
  FAIcons(FontAwesomeIcons.swimmer, 'swimmer'),
  FAIcons(FontAwesomeIcons.swimmingPool, 'swimmingPool'),
  FAIcons(FontAwesomeIcons.synagogue, 'synagogue'),
  FAIcons(FontAwesomeIcons.sync, 'sync'),
  FAIcons(FontAwesomeIcons.syncAlt, 'syncAlt'),
  FAIcons(FontAwesomeIcons.syringe, 'syringe'),
  FAIcons(FontAwesomeIcons.table, 'table'),
  FAIcons(FontAwesomeIcons.tableTennis, 'tableTennis'),
  FAIcons(FontAwesomeIcons.tablet, 'tablet'),
  FAIcons(FontAwesomeIcons.tabletAlt, 'tabletAlt'),
  FAIcons(FontAwesomeIcons.tablets, 'tablets'),
  FAIcons(FontAwesomeIcons.tachometerAlt, 'tachometerAlt'),
  FAIcons(FontAwesomeIcons.tag, 'tag'),
  FAIcons(FontAwesomeIcons.tags, 'tags'),
  FAIcons(FontAwesomeIcons.tape, 'tape'),
  FAIcons(FontAwesomeIcons.tasks, 'tasks'),
  FAIcons(FontAwesomeIcons.taxi, 'taxi'),
  FAIcons(FontAwesomeIcons.teamspeak, 'teamspeak'),
  FAIcons(FontAwesomeIcons.teeth, 'teeth'),
  FAIcons(FontAwesomeIcons.teethOpen, 'teethOpen'),
  FAIcons(FontAwesomeIcons.telegram, 'telegram'),
  FAIcons(FontAwesomeIcons.telegramPlane, 'telegramPlane'),
  FAIcons(FontAwesomeIcons.temperatureHigh, 'temperatureHigh'),
  FAIcons(FontAwesomeIcons.temperatureLow, 'temperatureLow'),
  FAIcons(FontAwesomeIcons.tencentWeibo, 'tencentWeibo'),
  FAIcons(FontAwesomeIcons.tenge, 'tenge'),
  FAIcons(FontAwesomeIcons.terminal, 'terminal'),
  FAIcons(FontAwesomeIcons.textHeight, 'textHeight'),
  FAIcons(FontAwesomeIcons.textWidth, 'textWidth'),
  FAIcons(FontAwesomeIcons.th, 'th'),
  FAIcons(FontAwesomeIcons.thLarge, 'thLarge'),
  FAIcons(FontAwesomeIcons.thList, 'thList'),
  FAIcons(FontAwesomeIcons.theRedYeti, 'theRedYeti'),
  FAIcons(FontAwesomeIcons.theaterMasks, 'theaterMasks'),
  FAIcons(FontAwesomeIcons.themeco, 'themeco'),
  FAIcons(FontAwesomeIcons.themeisle, 'themeisle'),
  FAIcons(FontAwesomeIcons.thermometer, 'thermometer'),
  FAIcons(FontAwesomeIcons.thermometerEmpty, 'thermometerEmpty'),
  FAIcons(FontAwesomeIcons.thermometerFull, 'thermometerFull'),
  FAIcons(FontAwesomeIcons.thermometerHalf, 'thermometerHalf'),
  FAIcons(FontAwesomeIcons.thermometerQuarter, 'thermometerQuarter'),
  FAIcons(
      FontAwesomeIcons.thermometerThreeQuarters, 'thermometerThreeQuarters'),
  FAIcons(FontAwesomeIcons.thinkPeaks, 'thinkPeaks'),
  FAIcons(FontAwesomeIcons.thumbsDown, 'thumbsDown'),
  FAIcons(FontAwesomeIcons.solidThumbsDown, 'solidThumbsDown'),
  FAIcons(FontAwesomeIcons.thumbsUp, 'thumbsUp'),
  FAIcons(FontAwesomeIcons.solidThumbsUp, 'solidThumbsUp'),
  FAIcons(FontAwesomeIcons.thumbtack, 'thumbtack'),
  FAIcons(FontAwesomeIcons.ticketAlt, 'ticketAlt'),
  FAIcons(FontAwesomeIcons.times, 'times'),
  FAIcons(FontAwesomeIcons.timesCircle, 'timesCircle'),
  FAIcons(FontAwesomeIcons.solidTimesCircle, 'solidTimesCircle'),
  FAIcons(FontAwesomeIcons.tint, 'tint'),
  FAIcons(FontAwesomeIcons.tintSlash, 'tintSlash'),
  FAIcons(FontAwesomeIcons.tired, 'tired'),
  FAIcons(FontAwesomeIcons.solidTired, 'solidTired'),
  FAIcons(FontAwesomeIcons.toggleOff, 'toggleOff'),
  FAIcons(FontAwesomeIcons.toggleOn, 'toggleOn'),
  FAIcons(FontAwesomeIcons.toilet, 'toilet'),
  FAIcons(FontAwesomeIcons.toiletPaper, 'toiletPaper'),
  FAIcons(FontAwesomeIcons.toolbox, 'toolbox'),
  FAIcons(FontAwesomeIcons.tools, 'tools'),
  FAIcons(FontAwesomeIcons.tooth, 'tooth'),
  FAIcons(FontAwesomeIcons.torah, 'torah'),
  FAIcons(FontAwesomeIcons.toriiGate, 'toriiGate'),
  FAIcons(FontAwesomeIcons.tractor, 'tractor'),
  FAIcons(FontAwesomeIcons.tradeFederation, 'tradeFederation'),
  FAIcons(FontAwesomeIcons.trademark, 'trademark'),
  FAIcons(FontAwesomeIcons.trafficLight, 'trafficLight'),
  FAIcons(FontAwesomeIcons.train, 'train'),
  FAIcons(FontAwesomeIcons.tram, 'tram'),
  FAIcons(FontAwesomeIcons.transgender, 'transgender'),
  FAIcons(FontAwesomeIcons.transgenderAlt, 'transgenderAlt'),
  FAIcons(FontAwesomeIcons.trash, 'trash'),
  FAIcons(FontAwesomeIcons.trashAlt, 'trashAlt'),
  FAIcons(FontAwesomeIcons.solidTrashAlt, 'solidTrashAlt'),
  FAIcons(FontAwesomeIcons.trashRestore, 'trashRestore'),
  FAIcons(FontAwesomeIcons.trashRestoreAlt, 'trashRestoreAlt'),
  FAIcons(FontAwesomeIcons.tree, 'tree'),
  FAIcons(FontAwesomeIcons.trello, 'trello'),
  FAIcons(FontAwesomeIcons.tripadvisor, 'tripadvisor'),
  FAIcons(FontAwesomeIcons.trophy, 'trophy'),
  FAIcons(FontAwesomeIcons.truck, 'truck'),
  FAIcons(FontAwesomeIcons.truckLoading, 'truckLoading'),
  FAIcons(FontAwesomeIcons.truckMonster, 'truckMonster'),
  FAIcons(FontAwesomeIcons.truckMoving, 'truckMoving'),
  FAIcons(FontAwesomeIcons.truckPickup, 'truckPickup'),
  FAIcons(FontAwesomeIcons.tshirt, 'tshirt'),
  FAIcons(FontAwesomeIcons.tty, 'tty'),
  FAIcons(FontAwesomeIcons.tumblr, 'tumblr'),
  FAIcons(FontAwesomeIcons.tumblrSquare, 'tumblrSquare'),
  FAIcons(FontAwesomeIcons.tv, 'tv'),
  FAIcons(FontAwesomeIcons.twitch, 'twitch'),
  FAIcons(FontAwesomeIcons.twitter, 'twitter'),
  FAIcons(FontAwesomeIcons.twitterSquare, 'twitterSquare'),
  FAIcons(FontAwesomeIcons.typo3, 'typo3'),
  FAIcons(FontAwesomeIcons.uber, 'uber'),
  FAIcons(FontAwesomeIcons.ubuntu, 'ubuntu'),
  FAIcons(FontAwesomeIcons.uikit, 'uikit'),
  FAIcons(FontAwesomeIcons.umbrella, 'umbrella'),
  FAIcons(FontAwesomeIcons.umbrellaBeach, 'umbrellaBeach'),
  FAIcons(FontAwesomeIcons.underline, 'underline'),
  FAIcons(FontAwesomeIcons.undo, 'undo'),
  FAIcons(FontAwesomeIcons.undoAlt, 'undoAlt'),
  FAIcons(FontAwesomeIcons.uniregistry, 'uniregistry'),
  FAIcons(FontAwesomeIcons.universalAccess, 'universalAccess'),
  FAIcons(FontAwesomeIcons.university, 'university'),
  FAIcons(FontAwesomeIcons.unlink, 'unlink'),
  FAIcons(FontAwesomeIcons.unlock, 'unlock'),
  FAIcons(FontAwesomeIcons.unlockAlt, 'unlockAlt'),
  FAIcons(FontAwesomeIcons.untappd, 'untappd'),
  FAIcons(FontAwesomeIcons.upload, 'upload'),
  FAIcons(FontAwesomeIcons.ups, 'ups'),
  FAIcons(FontAwesomeIcons.usb, 'usb'),
  FAIcons(FontAwesomeIcons.user, 'user'),
  FAIcons(FontAwesomeIcons.solidUser, 'solidUser'),
  FAIcons(FontAwesomeIcons.userAlt, 'userAlt'),
  FAIcons(FontAwesomeIcons.userAltSlash, 'userAltSlash'),
  FAIcons(FontAwesomeIcons.userAstronaut, 'userAstronaut'),
  FAIcons(FontAwesomeIcons.userCheck, 'userCheck'),
  FAIcons(FontAwesomeIcons.userCircle, 'userCircle'),
  FAIcons(FontAwesomeIcons.solidUserCircle, 'solidUserCircle'),
  FAIcons(FontAwesomeIcons.userClock, 'userClock'),
  FAIcons(FontAwesomeIcons.userCog, 'userCog'),
  FAIcons(FontAwesomeIcons.userEdit, 'userEdit'),
  FAIcons(FontAwesomeIcons.userFriends, 'userFriends'),
  FAIcons(FontAwesomeIcons.userGraduate, 'userGraduate'),
  FAIcons(FontAwesomeIcons.userInjured, 'userInjured'),
  FAIcons(FontAwesomeIcons.userLock, 'userLock'),
  FAIcons(FontAwesomeIcons.userMd, 'userMd'),
  FAIcons(FontAwesomeIcons.userMinus, 'userMinus'),
  FAIcons(FontAwesomeIcons.userNinja, 'userNinja'),
  FAIcons(FontAwesomeIcons.userNurse, 'userNurse'),
  FAIcons(FontAwesomeIcons.userPlus, 'userPlus'),
  FAIcons(FontAwesomeIcons.userSecret, 'userSecret'),
  FAIcons(FontAwesomeIcons.userShield, 'userShield'),
  FAIcons(FontAwesomeIcons.userSlash, 'userSlash'),
  FAIcons(FontAwesomeIcons.userTag, 'userTag'),
  FAIcons(FontAwesomeIcons.userTie, 'userTie'),
  FAIcons(FontAwesomeIcons.userTimes, 'userTimes'),
  FAIcons(FontAwesomeIcons.users, 'users'),
  FAIcons(FontAwesomeIcons.usersCog, 'usersCog'),
  FAIcons(FontAwesomeIcons.usps, 'usps'),
  FAIcons(FontAwesomeIcons.ussunnah, 'ussunnah'),
  FAIcons(FontAwesomeIcons.utensilSpoon, 'utensilSpoon'),
  FAIcons(FontAwesomeIcons.utensils, 'utensils'),
  FAIcons(FontAwesomeIcons.vaadin, 'vaadin'),
  FAIcons(FontAwesomeIcons.vectorSquare, 'vectorSquare'),
  FAIcons(FontAwesomeIcons.venus, 'venus'),
  FAIcons(FontAwesomeIcons.venusDouble, 'venusDouble'),
  FAIcons(FontAwesomeIcons.venusMars, 'venusMars'),
  FAIcons(FontAwesomeIcons.viacoin, 'viacoin'),
  FAIcons(FontAwesomeIcons.viadeo, 'viadeo'),
  FAIcons(FontAwesomeIcons.viadeoSquare, 'viadeoSquare'),
  FAIcons(FontAwesomeIcons.vial, 'vial'),
  FAIcons(FontAwesomeIcons.vials, 'vials'),
  FAIcons(FontAwesomeIcons.viber, 'viber'),
  FAIcons(FontAwesomeIcons.video, 'video'),
  FAIcons(FontAwesomeIcons.videoSlash, 'videoSlash'),
  FAIcons(FontAwesomeIcons.vihara, 'vihara'),
  FAIcons(FontAwesomeIcons.vimeo, 'vimeo'),
  FAIcons(FontAwesomeIcons.vimeoSquare, 'vimeoSquare'),
  FAIcons(FontAwesomeIcons.vimeoV, 'vimeoV'),
  FAIcons(FontAwesomeIcons.vine, 'vine'),
  FAIcons(FontAwesomeIcons.vk, 'vk'),
  FAIcons(FontAwesomeIcons.vnv, 'vnv'),
  FAIcons(FontAwesomeIcons.volleyballBall, 'volleyballBall'),
  FAIcons(FontAwesomeIcons.volumeDown, 'volumeDown'),
  FAIcons(FontAwesomeIcons.volumeMute, 'volumeMute'),
  FAIcons(FontAwesomeIcons.volumeOff, 'volumeOff'),
  FAIcons(FontAwesomeIcons.volumeUp, 'volumeUp'),
  FAIcons(FontAwesomeIcons.voteYea, 'voteYea'),
  FAIcons(FontAwesomeIcons.vrCardboard, 'vrCardboard'),
  FAIcons(FontAwesomeIcons.vuejs, 'vuejs'),
  FAIcons(FontAwesomeIcons.walking, 'walking'),
  FAIcons(FontAwesomeIcons.wallet, 'wallet'),
  FAIcons(FontAwesomeIcons.warehouse, 'warehouse'),
  FAIcons(FontAwesomeIcons.water, 'water'),
  FAIcons(FontAwesomeIcons.weebly, 'weebly'),
  FAIcons(FontAwesomeIcons.weibo, 'weibo'),
  FAIcons(FontAwesomeIcons.weight, 'weight'),
  FAIcons(FontAwesomeIcons.weightHanging, 'weightHanging'),
  FAIcons(FontAwesomeIcons.weixin, 'weixin'),
  FAIcons(FontAwesomeIcons.whatsapp, 'whatsapp'),
  FAIcons(FontAwesomeIcons.whatsappSquare, 'whatsappSquare'),
  FAIcons(FontAwesomeIcons.wheelchair, 'wheelchair'),
  FAIcons(FontAwesomeIcons.whmcs, 'whmcs'),
  FAIcons(FontAwesomeIcons.wifi, 'wifi'),
  FAIcons(FontAwesomeIcons.wikipediaW, 'wikipediaW'),
  FAIcons(FontAwesomeIcons.wind, 'wind'),
  FAIcons(FontAwesomeIcons.windowClose, 'windowClose'),
  FAIcons(FontAwesomeIcons.solidWindowClose, 'solidWindowClose'),
  FAIcons(FontAwesomeIcons.windowMaximize, 'windowMaximize'),
  FAIcons(FontAwesomeIcons.solidWindowMaximize, 'solidWindowMaximize'),
  FAIcons(FontAwesomeIcons.windowMinimize, 'windowMinimize'),
  FAIcons(FontAwesomeIcons.solidWindowMinimize, 'solidWindowMinimize'),
  FAIcons(FontAwesomeIcons.windowRestore, 'windowRestore'),
  FAIcons(FontAwesomeIcons.solidWindowRestore, 'solidWindowRestore'),
  FAIcons(FontAwesomeIcons.windows, 'windows'),
  FAIcons(FontAwesomeIcons.wineBottle, 'wineBottle'),
  FAIcons(FontAwesomeIcons.wineGlass, 'wineGlass'),
  FAIcons(FontAwesomeIcons.wineGlassAlt, 'wineGlassAlt'),
  FAIcons(FontAwesomeIcons.wix, 'wix'),
  FAIcons(FontAwesomeIcons.wizardsOfTheCoast, 'wizardsOfTheCoast'),
  FAIcons(FontAwesomeIcons.wolfPackBattalion, 'wolfPackBattalion'),
  FAIcons(FontAwesomeIcons.wonSign, 'wonSign'),
  FAIcons(FontAwesomeIcons.wordpress, 'wordpress'),
  FAIcons(FontAwesomeIcons.wordpressSimple, 'wordpressSimple'),
  FAIcons(FontAwesomeIcons.wpbeginner, 'wpbeginner'),
  FAIcons(FontAwesomeIcons.wpexplorer, 'wpexplorer'),
  FAIcons(FontAwesomeIcons.wpforms, 'wpforms'),
  FAIcons(FontAwesomeIcons.wpressr, 'wpressr'),
  FAIcons(FontAwesomeIcons.wrench, 'wrench'),
  FAIcons(FontAwesomeIcons.xRay, 'xRay'),
  FAIcons(FontAwesomeIcons.xbox, 'xbox'),
  FAIcons(FontAwesomeIcons.xing, 'xing'),
  FAIcons(FontAwesomeIcons.xingSquare, 'xingSquare'),
  FAIcons(FontAwesomeIcons.yCombinator, 'yCombinator'),
  FAIcons(FontAwesomeIcons.yahoo, 'yahoo'),
  FAIcons(FontAwesomeIcons.yandex, 'yandex'),
  FAIcons(FontAwesomeIcons.yandexInternational, 'yandexInternational'),
  FAIcons(FontAwesomeIcons.yarn, 'yarn'),
  FAIcons(FontAwesomeIcons.yelp, 'yelp'),
  FAIcons(FontAwesomeIcons.yenSign, 'yenSign'),
  FAIcons(FontAwesomeIcons.yinYang, 'yinYang'),
  FAIcons(FontAwesomeIcons.yoast, 'yoast'),
  FAIcons(FontAwesomeIcons.youtube, 'youtube'),
  FAIcons(FontAwesomeIcons.youtubeSquare, 'youtubeSquare'),
  FAIcons(FontAwesomeIcons.zhihu, 'zhihu'),
];
