name: gclone
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^0.11.4
  animated_floatactionbuttons: ^0.1.0
  package_info: ^0.4.0+17
  path_provider: ^1.6.7
  provider: ^4.0.5
  simple_animations: ^1.3.12
  shared_preferences: ^0.5.7
  url_launcher: ^5.4.5
  font_awesome_flutter: ^8.8.1
  file_picker:
  path_morph: 1.0.1
  fl_chart:
    path: ../../_programming/go/src/github.com/instance-id/fl_chart
  intl: ^0.16.1
  meta: ^1.1.8
  common_utils: ^1.1.3
  shape_of_view: ^1.0.2
  flutter_villains: ^1.2.1
  collection: ^1.14.12
  flutter_form_builder: ^3.8.3
#    git:
#      url: git://github.com/instance-id/bezier-chart.git
#      ref: mouse_tracking

  webview_flutter: ^0.3.20+2
  dart_apex_charts:
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway/Raleway-Regular.ttf
        - asset: fonts/Raleway/Raleway-Thin.ttf
          style: normal
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
    - family: Digital
      fonts:
        - asset: fonts/digital-7.ttf

  assets:
    # *Tip*: keep the slash at the end of folder path adds all files to
    # assets. Note: this doesn't work with subfolders.
    # c.f. https://github.com/flutter/flutter/issues/4890#issuecomment-407327749
    - lib/routes/
    - res/images/
    - desktop/assets/drive-steering-wheel.jpg
    - desktop/assets/line.png
    - assets/index.html
    # - packages/flutter_gallery_assets/animated_images/animated_flutter_stickers.webp
