name: gclone
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  after_layout: ^1.0.7+2
  animated_floatactionbuttons: ^0.1.0
  clipboard_manager: ^0.0.4
  package_info: ^0.4.0+6
  path_provider: ^1.2.0
  provider: ^3.0.0+1
  scoped_model: ^1.0.1
  simple_animations: ^1.3.3
  shared_preferences: ^0.5.3+4
  url_launcher: ^5.1.1
  font_awesome_flutter: ^8.5.0
  file_picker:
  path_morph: 1.0.1
  fl_chart: ^0.1.5
  fcharts:
  charts_flutter: ^0.6.0
  intl: ^0.15.8
  meta: ^1.1.1
  collection: ^1.14.11
  bezier_chart:
    path: /home/mosthated/_dev/programming/go/src/github.com/instance-id/bezier-chart
#    git:
#      url: git://github.com/instance-id/bezier-chart.git
#      ref: mouse_tracking

  webview_flutter: ^0.3.10+4
  dart_apex_charts:
#  fuchsia_webview_flutter:
#    git:
#      url: git@github.com:fuchsia-rs/topaz-rs.git
#      path: public/dart/fuchsia_webview_flutter/
#  fuchsia_modular:
#    git:
#      url: git@github.com:fuchsia-rs/topaz-rs.git
#      path: public/dart/fuchsia_modular/
#  fuchsia_flutter:
#    git:
#      url: git@github.com:fuchsia-rs/topaz-rs.git
#      path: public/dart/fuchsia_flutter/
#  fuchsia_services:
#    git:
#      url: git@github.com:fuchsia-rs/topaz-rs.git
#      path: public/dart/fuchsia_services/
#  fuchsia_scenic_flutter:
#    git:
#      url: git@github.com:fuchsia-rs/topaz-rs.git
#      path: public/dart/fuchsia_scenic_flutter/
#  fidl:
#    git:
#      url: git@github.com:fuchsia-rs/topaz-rs.git
#      path: public/dart/fidl/
#  fuchsia_scenic:
#    git:
#      url: git@github.com:fuchsia-rs/topaz-rs.git
#      path: public/dart/fuchsia_scenic/
#  fuchsia_logger:
#    git:
#      url: git@github.com:fuchsia-rs/topaz-rs.git
#      path: public/dart/fuchsia_logger/
#  zircon:
#    git:
#      url: git@github.com:fuchsia-rs/topaz-rs.git
#      path: public/dart/zircon/
#  fuchsia_vfs:
#    git:
#      url: git@github.com:fuchsia-rs/topaz-rs.git
#      path: public/dart/fuchsia_vfs/




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway/Raleway-Regular.ttf
        - asset: fonts/Raleway/Raleway-Thin.ttf
          style: normal
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
    - family: Digital
      fonts:
        - asset: fonts/digital-7.ttf

  assets:
    # *Tip*: keep the slash at the end of folder path adds all files to
    # assets. Note: this doesn't work with subfolders.
    # c.f. https://github.com/flutter/flutter/issues/4890#issuecomment-407327749
    - lib/routes/
    - res/images/
    - desktop/assets/drive-steering-wheel.jpg
    - desktop/assets/line.png
    - assets/index.html
    # - packages/flutter_gallery_assets/animated_images/animated_flutter_stickers.webp
